// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke.objecttypes;

import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke.datatypes.EnergySourceEnumeration;
import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.nodes.Mandatory;
import com.prosysopc.ua.nodes.UaProperty;
import java.lang.Boolean;
import java.lang.String;

/**
 * Generated on 2025-04-16 18:27:26
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1011")
public interface CombiSteamerDeviceType extends CommercialKitchenDeviceType {
  String ENERGY_SOURCE = "EnergySource";

  String IS_WITH_AUTOMATIC_CLEANING = "IsWithAutomaticCleaning";

  String IS_WITH_EXTERNAL_CORE_TEMP_SENSOR = "IsWithExternalCoreTempSensor";

  String IS_WITH_INTERNAL_CORE_TEMP_SENSOR = "IsWithInternalCoreTempSensor";

  String IS_WITH_SOUSVIDE_TEMP_SENSOR = "IsWithSousvideTempSensor";

  String COMBI_STEAMER = "CombiSteamer";

  @Mandatory
  UaProperty getEnergySourceNode();

  @Mandatory
  EnergySourceEnumeration getEnergySource();

  @Mandatory
  void setEnergySource(EnergySourceEnumeration value) throws StatusException;

  @Mandatory
  UaProperty getIsWithAutomaticCleaningNode();

  @Mandatory
  Boolean isIsWithAutomaticCleaning();

  @Mandatory
  void setIsWithAutomaticCleaning(Boolean value) throws StatusException;

  @Mandatory
  UaProperty getIsWithExternalCoreTempSensorNode();

  @Mandatory
  Boolean isIsWithExternalCoreTempSensor();

  @Mandatory
  void setIsWithExternalCoreTempSensor(Boolean value) throws StatusException;

  @Mandatory
  UaProperty getIsWithInternalCoreTempSensorNode();

  @Mandatory
  Boolean isIsWithInternalCoreTempSensor();

  @Mandatory
  void setIsWithInternalCoreTempSensor(Boolean value) throws StatusException;

  @Mandatory
  UaProperty getIsWithSousvideTempSensorNode();

  @Mandatory
  Boolean isIsWithSousvideTempSensor();

  @Mandatory
  void setIsWithSousvideTempSensor(Boolean value) throws StatusException;

  @Mandatory
  CombiSteamerParameterType getCombiSteamerNode();
}
