// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke.objecttypes;

import com.prosysopc.ua.TypeDefinitionId;
import java.lang.String;

/**
 * Generated on 2024-09-09 10:35:47
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1013")
public interface OvenDeviceType extends CommercialKitchenDeviceType {
  String CHAMBER___NO__ = "Chamber_<No.>";
}
