// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke.objecttypes;

import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke.datatypes.EnergySourceEnumeration;
import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.nodes.Mandatory;
import com.prosysopc.ua.nodes.UaProperty;
import java.lang.String;

/**
 * Generated on 2024-09-09 10:35:47
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1015")
public interface PressureCookingKettleDeviceType extends CommercialKitchenDeviceType {
  String ENERGY_SOURCE = "EnergySource";

  String PRESSURE_COOKING_KETTLE = "PressureCookingKettle";

  @Mandatory
  UaProperty getEnergySourceNode();

  @Mandatory
  EnergySourceEnumeration getEnergySource();

  @Mandatory
  void setEnergySource(EnergySourceEnumeration value) throws StatusException;

  @Mandatory
  PressureCookingKettleParameterType getPressureCookingKettleNode();
}
