// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.server;

import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.CheckFunctionAlarmType;
import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.server.GeneratedNodeInitializer;
import com.prosysopc.ua.server.NodeManagerUaNode;
import com.prosysopc.ua.server.ServiceContext;
import com.prosysopc.ua.stack.builtintypes.DiagnosticInfo;
import com.prosysopc.ua.stack.builtintypes.LocalizedText;
import com.prosysopc.ua.stack.builtintypes.NodeId;
import com.prosysopc.ua.stack.builtintypes.QualifiedName;
import com.prosysopc.ua.stack.builtintypes.StatusCode;
import com.prosysopc.ua.stack.builtintypes.Variant;
import java.lang.Override;

/**
 * Generated on 2022-10-10 10:21:30
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/DI/;i=15441")
public abstract class CheckFunctionAlarmTypeNodeBase extends DeviceHealthDiagnosticAlarmTypeNode implements CheckFunctionAlarmType {
  private static GeneratedNodeInitializer<CheckFunctionAlarmTypeNode> f_checkFunctionAlarmTypeNodeInitializer;

  protected CheckFunctionAlarmTypeNodeBase(NodeManagerUaNode nodeManager, NodeId nodeId,
      QualifiedName browseName, LocalizedText displayName) {
    super(nodeManager, nodeId, browseName, displayName);
  }

  @Override
  public void afterCreate() {
    super.afterCreate();

    // Call afterCreate for each sub-node (if the node has any)
    GeneratedNodeInitializer<CheckFunctionAlarmTypeNode> impl = getCheckFunctionAlarmTypeNodeInitializer();
    if(impl != null) {
      impl.init((CheckFunctionAlarmTypeNode)this);
    }
  }

  public static GeneratedNodeInitializer<CheckFunctionAlarmTypeNode> getCheckFunctionAlarmTypeNodeInitializer() {
    return f_checkFunctionAlarmTypeNodeInitializer;
  }

  public static void setCheckFunctionAlarmTypeNodeInitializer(GeneratedNodeInitializer<CheckFunctionAlarmTypeNode> f_checkFunctionAlarmTypeNodeInitializerNewValue) {
    f_checkFunctionAlarmTypeNodeInitializer=f_checkFunctionAlarmTypeNodeInitializerNewValue;
  }

  @Override
  public Variant[] callMethod(ServiceContext serviceContext, NodeId methodId,
      Variant[] inputArguments, StatusCode[] inputArgumentResults,
      DiagnosticInfo[] inputArgumentDiagnosticInfos) throws StatusException {
    return super.callMethod(serviceContext, methodId, inputArguments, inputArgumentResults, inputArgumentDiagnosticInfos);
  }
}
