// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.server;

import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.DIDataTypeDictionaryHelper;
import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.DISerializers;
import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.DeviceHealthEnumeration;
import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.FetchResultDataType;
import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.ParameterResultDataType;
import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.SoftwareVersionFileType;
import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.TransferResultDataDataType;
import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.TransferResultErrorDataType;
import com.prosysopc.ua.server.ServerCodegenModel;
import com.prosysopc.ua.server.ServerCodegenModelProvider;
import java.lang.Override;
import java.lang.RuntimeException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;

/**
 * Generated on 2022-10-10 10:21:30
 */
public class DIServerInformationModel implements ServerCodegenModelProvider {
  public static final ServerCodegenModel MODEL;

  static {
    ServerCodegenModel.Builder b = ServerCodegenModel.builder();
    b.addClass(TopologyElementTypeNode.class);
    b.addClass(IVendorNameplateTypeNode.class);
    b.addClass(ITagNameplateTypeNode.class);
    b.addClass(IDeviceHealthTypeNode.class);
    b.addClass(ISupportInfoTypeNode.class);
    b.addClass(ComponentTypeNode.class);
    b.addClass(DeviceTypeNode.class);
    b.addClass(SoftwareTypeNode.class);
    b.addClass(BlockTypeNode.class);
    b.addClass(DeviceHealthDiagnosticAlarmTypeNode.class);
    b.addClass(FailureAlarmTypeNode.class);
    b.addClass(CheckFunctionAlarmTypeNode.class);
    b.addClass(OffSpecAlarmTypeNode.class);
    b.addClass(MaintenanceRequiredAlarmTypeNode.class);
    b.addClass(ConfigurableObjectTypeNode.class);
    b.addClass(FunctionalGroupTypeNode.class);
    b.addClass(ProtocolTypeNode.class);
    b.addClass(UIElementTypeNode.class);
    b.addClass(NetworkTypeNode.class);
    b.addClass(ConnectionPointTypeNode.class);
    b.addClass(TransferServicesTypeNode.class);
    b.addClass(LockingServicesTypeNode.class);
    b.addClass(SoftwareUpdateTypeNode.class);
    b.addClass(SoftwareLoadingTypeNode.class);
    b.addClass(PackageLoadingTypeNode.class);
    b.addClass(DirectLoadingTypeNode.class);
    b.addClass(CachedLoadingTypeNode.class);
    b.addClass(FileSystemLoadingTypeNode.class);
    b.addClass(SoftwareVersionTypeNode.class);
    b.addClass(PrepareForUpdateStateMachineTypeNode.class);
    b.addClass(InstallationStateMachineTypeNode.class);
    b.addClass(PowerCycleStateMachineTypeNode.class);
    b.addClass(ConfirmationStateMachineTypeNode.class);
    b.addSerializers(DISerializers.SERIALIZERS);
    b.setDataTypeDictionary(DIDataTypeDictionaryHelper.createDataTypeDictionary());
    b.addStructureSpecification(FetchResultDataType.SPECIFICATION);
    b.addStructureSpecification(TransferResultErrorDataType.SPECIFICATION);
    b.addStructureSpecification(TransferResultDataDataType.SPECIFICATION);
    b.addStructureSpecification(ParameterResultDataType.SPECIFICATION);
    b.addEnumerationSpecification(DeviceHealthEnumeration.SPECIFICATION);
    b.addEnumerationSpecification(SoftwareVersionFileType.SPECIFICATION);
    MODEL = b.build();
  }

  @Override
  public ServerCodegenModel get() {
    return MODEL;
  }

  /**
   * Returns URI for the NodeSet XML file 'Opc.Ua.Di.NodeSet2.xml', assuming it is put into classpath next to classfile of this class. You can use the 'server_model' codegen target to do it automatically as part of the code generation. If the file is not found this method will throw RuntimeException.
   */
  public static URI getLocationURI() {
    URL nodeset = DIServerInformationModel.class.getResource("Opc.Ua.Di.NodeSet2.xml");
    if (nodeset == null) {
      throw new RuntimeException("Cannot find nodeset 'Opc.Ua.Di.NodeSet2.xml' in classpath next to "+DIServerInformationModel.class);
    }
    try {
      return nodeset.toURI();
    } catch (URISyntaxException e) {
      throw new RuntimeException(e);
    }
  }
}
