// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.server;

import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.server.ServiceContext;
import com.prosysopc.ua.stack.builtintypes.ByteString;
import java.lang.String;

public abstract interface InstallationStateMachineTypeInstallSoftwarePackageMethod {
  void installSoftwarePackage(ServiceContext serviceContext, InstallationStateMachineTypeNode node,
      String f_manufacturerUri, String f_softwareRevision, String[] f_patchIdentifiers,
      ByteString f_hash) throws StatusException;
}
