// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.server;

import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.server.ServiceContext;
import com.prosysopc.ua.stack.builtintypes.Structure;
import java.lang.Boolean;
import java.lang.Integer;

public abstract interface TransferServicesTypeFetchTransferResultDataMethod {
  Structure fetchTransferResultData(ServiceContext serviceContext, TransferServicesTypeNode node,
      Integer f_transferID, Integer f_sequenceNumber, Integer f_maxParameterResultsToReturn,
      Boolean f_omitGoodResults) throws StatusException;
}
