// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.server;

import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.TransferServicesType;
import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.server.ServiceContext;

public abstract interface TransferServicesTypeTransferFromDeviceMethod {
  TransferServicesType.TransferFromDeviceMethodOutputs transferFromDevice(ServiceContext serviceContext,
      TransferServicesTypeNode node) throws StatusException;
}
