// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di;

import com.prosysopc.ua.stack.builtintypes.ExpandedNodeId;
import com.prosysopc.ua.stack.builtintypes.UnsignedInteger;

class DIDataTypeIdsInit {
  static ExpandedNodeId initDeviceHealthEnumeration() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6244L));
  }

  static ExpandedNodeId initFetchResultDataType() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6522L));
  }

  static ExpandedNodeId initTransferResultErrorDataType() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15888L));
  }

  static ExpandedNodeId initTransferResultDataDataType() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15889L));
  }

  static ExpandedNodeId initParameterResultDataType() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6525L));
  }

  static ExpandedNodeId initSoftwareVersionFileType() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(331L));
  }

  static ExpandedNodeId initUpdateBehavior() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(333L));
  }
}
