// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di;

import com.prosysopc.ua.stack.builtintypes.ExpandedNodeId;
import java.util.Set;

/**
 * Generated on 2024-06-17 14:43:47
 */
public interface DIDataTypeIds {
  ExpandedNodeId DeviceHealthEnumeration = DIUaIds.DeviceHealthEnumeration.asExpandedNodeId();

  ExpandedNodeId FetchResultDataType = DIUaIds.FetchResultDataType.asExpandedNodeId();

  ExpandedNodeId TransferResultErrorDataType = DIUaIds.TransferResultErrorDataType.asExpandedNodeId();

  ExpandedNodeId TransferResultDataDataType = DIUaIds.TransferResultDataDataType.asExpandedNodeId();

  ExpandedNodeId ParameterResultDataType = DIUaIds.ParameterResultDataType.asExpandedNodeId();

  ExpandedNodeId SoftwareVersionFileType = DIUaIds.SoftwareVersionFileType.asExpandedNodeId();

  ExpandedNodeId UpdateBehavior = DIUaIds.UpdateBehavior.asExpandedNodeId();

  static Set<ExpandedNodeId> allDataTypeIdentifiers() {
    return InternalDIDataTypeIdsHelper.ALL_DATATYPE_IDENTIFIERS;
  }
}
