// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di;

import com.prosysopc.ua.stack.builtintypes.ExpandedNodeId;

/**
 * Generated on 2022-10-10 10:21:30
 */
public interface DIMethodIds {
  ExpandedNodeId TopologyElementType_Lock_BreakLock = DIMethodIdsInit.initTopologyElementType_Lock_BreakLock();

  ExpandedNodeId TopologyElementType_Lock_InitLock = DIMethodIdsInit.initTopologyElementType_Lock_InitLock();

  ExpandedNodeId TopologyElementType_Lock_RenewLock = DIMethodIdsInit.initTopologyElementType_Lock_RenewLock();

  ExpandedNodeId TopologyElementType_Lock_ExitLock = DIMethodIdsInit.initTopologyElementType_Lock_ExitLock();

  ExpandedNodeId NetworkType_Lock_BreakLock = DIMethodIdsInit.initNetworkType_Lock_BreakLock();

  ExpandedNodeId NetworkType_Lock_ExitLock = DIMethodIdsInit.initNetworkType_Lock_ExitLock();

  ExpandedNodeId NetworkType_Lock_InitLock = DIMethodIdsInit.initNetworkType_Lock_InitLock();

  ExpandedNodeId NetworkType_Lock_RenewLock = DIMethodIdsInit.initNetworkType_Lock_RenewLock();

  ExpandedNodeId TransferServicesType_TransferToDevice = DIMethodIdsInit.initTransferServicesType_TransferToDevice();

  ExpandedNodeId TransferServicesType_TransferFromDevice = DIMethodIdsInit.initTransferServicesType_TransferFromDevice();

  ExpandedNodeId TransferServicesType_FetchTransferResultData = DIMethodIdsInit.initTransferServicesType_FetchTransferResultData();

  ExpandedNodeId LockingServicesType_BreakLock = DIMethodIdsInit.initLockingServicesType_BreakLock();

  ExpandedNodeId LockingServicesType_InitLock = DIMethodIdsInit.initLockingServicesType_InitLock();

  ExpandedNodeId LockingServicesType_RenewLock = DIMethodIdsInit.initLockingServicesType_RenewLock();

  ExpandedNodeId LockingServicesType_ExitLock = DIMethodIdsInit.initLockingServicesType_ExitLock();

  ExpandedNodeId SoftwareUpdateType_Confirmation_Confirm = DIMethodIdsInit.initSoftwareUpdateType_Confirmation_Confirm();

  ExpandedNodeId SoftwareUpdateType_Parameters_CloseAndCommit = DIMethodIdsInit.initSoftwareUpdateType_Parameters_CloseAndCommit();

  ExpandedNodeId SoftwareUpdateType_Installation_Resume = DIMethodIdsInit.initSoftwareUpdateType_Installation_Resume();

  ExpandedNodeId SoftwareUpdateType_PrepareForUpdate_Abort = DIMethodIdsInit.initSoftwareUpdateType_PrepareForUpdate_Abort();

  ExpandedNodeId SoftwareUpdateType_PrepareForUpdate_Prepare = DIMethodIdsInit.initSoftwareUpdateType_PrepareForUpdate_Prepare();

  ExpandedNodeId SoftwareUpdateType_Parameters_GenerateFileForWrite = DIMethodIdsInit.initSoftwareUpdateType_Parameters_GenerateFileForWrite();

  ExpandedNodeId SoftwareUpdateType_Parameters_GenerateFileForRead = DIMethodIdsInit.initSoftwareUpdateType_Parameters_GenerateFileForRead();

  ExpandedNodeId PackageLoadingType_FileTransfer_CloseAndCommit = DIMethodIdsInit.initPackageLoadingType_FileTransfer_CloseAndCommit();

  ExpandedNodeId PackageLoadingType_FileTransfer_GenerateFileForWrite = DIMethodIdsInit.initPackageLoadingType_FileTransfer_GenerateFileForWrite();

  ExpandedNodeId PackageLoadingType_FileTransfer_GenerateFileForRead = DIMethodIdsInit.initPackageLoadingType_FileTransfer_GenerateFileForRead();

  ExpandedNodeId CachedLoadingType_GetUpdateBehavior = DIMethodIdsInit.initCachedLoadingType_GetUpdateBehavior();

  ExpandedNodeId FileSystemLoadingType_FileSystem_CreateDirectory = DIMethodIdsInit.initFileSystemLoadingType_FileSystem_CreateDirectory();

  ExpandedNodeId FileSystemLoadingType_FileSystem_MoveOrCopy = DIMethodIdsInit.initFileSystemLoadingType_FileSystem_MoveOrCopy();

  ExpandedNodeId FileSystemLoadingType_GetUpdateBehavior = DIMethodIdsInit.initFileSystemLoadingType_GetUpdateBehavior();

  ExpandedNodeId FileSystemLoadingType_FileSystem_DeleteFileSystemObject = DIMethodIdsInit.initFileSystemLoadingType_FileSystem_DeleteFileSystemObject();

  ExpandedNodeId FileSystemLoadingType_FileSystem_CreateFile = DIMethodIdsInit.initFileSystemLoadingType_FileSystem_CreateFile();

  ExpandedNodeId FileSystemLoadingType_ValidateFiles = DIMethodIdsInit.initFileSystemLoadingType_ValidateFiles();

  ExpandedNodeId PrepareForUpdateStateMachineType_Prepare = DIMethodIdsInit.initPrepareForUpdateStateMachineType_Prepare();

  ExpandedNodeId PrepareForUpdateStateMachineType_Resume = DIMethodIdsInit.initPrepareForUpdateStateMachineType_Resume();

  ExpandedNodeId PrepareForUpdateStateMachineType_Abort = DIMethodIdsInit.initPrepareForUpdateStateMachineType_Abort();

  ExpandedNodeId InstallationStateMachineType_InstallFiles = DIMethodIdsInit.initInstallationStateMachineType_InstallFiles();

  ExpandedNodeId InstallationStateMachineType_InstallSoftwarePackage = DIMethodIdsInit.initInstallationStateMachineType_InstallSoftwarePackage();

  ExpandedNodeId InstallationStateMachineType_Resume = DIMethodIdsInit.initInstallationStateMachineType_Resume();

  ExpandedNodeId ConfirmationStateMachineType_Confirm = DIMethodIdsInit.initConfirmationStateMachineType_Confirm();
}
