// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di;

import com.prosysopc.ua.UaNamespace;

/**
 * Generated on 2024-09-09 10:35:45
 */
final class DIUaIdsInitHelper {
  static final UaNamespace NAMESPACE = UaNamespace.from("http://opcfoundation.org/UA/DI/");
}
