// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di;

import com.prosysopc.ua.UaNodeId;
import java.util.Set;

/**
 * Generated on 2025-04-16 18:27:23
 */
public interface DIUaDataTypeIds {
  UaNodeId DeviceHealthEnumeration = DIUaDataTypeIdsInit.initDeviceHealthEnumeration();

  UaNodeId FetchResultDataType = DIUaDataTypeIdsInit.initFetchResultDataType();

  UaNodeId TransferResultErrorDataType = DIUaDataTypeIdsInit.initTransferResultErrorDataType();

  UaNodeId TransferResultDataDataType = DIUaDataTypeIdsInit.initTransferResultDataDataType();

  UaNodeId ParameterResultDataType = DIUaDataTypeIdsInit.initParameterResultDataType();

  UaNodeId SoftwareVersionFileType = DIUaDataTypeIdsInit.initSoftwareVersionFileType();

  UaNodeId UpdateBehavior = DIUaDataTypeIdsInit.initUpdateBehavior();

  static Set<UaNodeId> allDataTypeIdentifiers() {
    return InternalDIUaDataTypeIdsHelper.ALL_DATATYPE_IDENTIFIERS;
  }
}
