// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di;

import com.prosysopc.ua.UaNamespace;

/**
 * Generated on 2024-06-17 14:43:47
 */
class DIUaIdsInitHelper {
  static UaNamespace NAMESPACE = UaNamespace.from("http://opcfoundation.org/UA/DI/");
}
