// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di;

import com.prosysopc.ua.UaNodeId;

/**
 * Generated on 2025-04-16 18:27:23
 */
class DIUaVariableTypeIdsInit {
  static UaNodeId initLifetimeVariableType() {
    return UaNodeId.numeric(DIUaIdsInitHelper.NAMESPACE, 468L);
  }

  static UaNodeId initUIElementType() {
    return UaNodeId.numeric(DIUaIdsInitHelper.NAMESPACE, 6246L);
  }
}
