// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di;

import com.prosysopc.ua.UaNodeId;

class DIUaDataTypeIdsInit {
  static UaNodeId initDeviceHealthEnumeration() {
    return UaNodeId.numeric(DIUaIdsInitHelper.NAMESPACE, 6244L);
  }

  static UaNodeId initFetchResultDataType() {
    return UaNodeId.numeric(DIUaIdsInitHelper.NAMESPACE, 6522L);
  }

  static UaNodeId initTransferResultErrorDataType() {
    return UaNodeId.numeric(DIUaIdsInitHelper.NAMESPACE, 15888L);
  }

  static UaNodeId initTransferResultDataDataType() {
    return UaNodeId.numeric(DIUaIdsInitHelper.NAMESPACE, 15889L);
  }

  static UaNodeId initParameterResultDataType() {
    return UaNodeId.numeric(DIUaIdsInitHelper.NAMESPACE, 6525L);
  }

  static UaNodeId initSoftwareVersionFileType() {
    return UaNodeId.numeric(DIUaIdsInitHelper.NAMESPACE, 331L);
  }

  static UaNodeId initUpdateBehavior() {
    return UaNodeId.numeric(DIUaIdsInitHelper.NAMESPACE, 333L);
  }
}
