// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di;

import com.prosysopc.ua.stack.builtintypes.ExpandedNodeId;
import com.prosysopc.ua.stack.builtintypes.UnsignedInteger;

class DIVariableIdsInit {
  static ExpandedNodeId initTopologyElementType_Lock_RemainingLockTime() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6165L));
  }

  static ExpandedNodeId initTopologyElementType_Lock_InitLock_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6168L));
  }

  static ExpandedNodeId initTopologyElementType_Lock_Locked() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6468L));
  }

  static ExpandedNodeId initTopologyElementType_Lock_LockingClient() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6163L));
  }

  static ExpandedNodeId initTopologyElementType_Lock_InitLock_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6167L));
  }

  static ExpandedNodeId initTopologyElementType_Lock_BreakLock_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6174L));
  }

  static ExpandedNodeId initTopologyElementType_Lock_LockingUser() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6164L));
  }

  static ExpandedNodeId initTopologyElementType_ParameterSet_ParameterIdentifier() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6017L));
  }

  static ExpandedNodeId initTopologyElementType_Lock_RenewLock_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6170L));
  }

  static ExpandedNodeId initTopologyElementType_Lock_ExitLock_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6172L));
  }

  static ExpandedNodeId initIVendorNameplateType_RevisionCounter() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15047L));
  }

  static ExpandedNodeId initIVendorNameplateType_PatchIdentifiers() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(24L));
  }

  static ExpandedNodeId initIVendorNameplateType_ManufacturerUri() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15037L));
  }

  static ExpandedNodeId initIVendorNameplateType_DeviceRevision() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15041L));
  }

  static ExpandedNodeId initIVendorNameplateType_ProductInstanceUri() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15046L));
  }

  static ExpandedNodeId initIVendorNameplateType_HardwareRevision() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15039L));
  }

  static ExpandedNodeId initIVendorNameplateType_SoftwareRevision() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15040L));
  }

  static ExpandedNodeId initIVendorNameplateType_DeviceManual() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15043L));
  }

  static ExpandedNodeId initIVendorNameplateType_SoftwareReleaseDate() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(23L));
  }

  static ExpandedNodeId initIVendorNameplateType_SerialNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15045L));
  }

  static ExpandedNodeId initIVendorNameplateType_Model() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15038L));
  }

  static ExpandedNodeId initIVendorNameplateType_Manufacturer() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15036L));
  }

  static ExpandedNodeId initIVendorNameplateType_ProductCode() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15042L));
  }

  static ExpandedNodeId initIVendorNameplateType_DeviceClass() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15044L));
  }

  static ExpandedNodeId initITagNameplateType_ComponentName() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15050L));
  }

  static ExpandedNodeId initITagNameplateType_AssetId() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15049L));
  }

  static ExpandedNodeId initIDeviceHealthType_DeviceHealth() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15052L));
  }

  static ExpandedNodeId initISupportInfoType_DeviceTypeImage_ImageIdentifier() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15056L));
  }

  static ExpandedNodeId initISupportInfoType_ImageSet_ImageIdentifier() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15062L));
  }

  static ExpandedNodeId initISupportInfoType_Documentation_DocumentIdentifier() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15058L));
  }

  static ExpandedNodeId initISupportInfoType_ProtocolSupport_ProtocolSupportIdentifier() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15060L));
  }

  static ExpandedNodeId initComponentType_Manufacturer() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15086L));
  }

  static ExpandedNodeId initComponentType_Model() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15088L));
  }

  static ExpandedNodeId initComponentType_RevisionCounter() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15097L));
  }

  static ExpandedNodeId initComponentType_ProductCode() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15092L));
  }

  static ExpandedNodeId initComponentType_SerialNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15095L));
  }

  static ExpandedNodeId initComponentType_DeviceClass() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15094L));
  }

  static ExpandedNodeId initComponentType_HardwareRevision() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15089L));
  }

  static ExpandedNodeId initComponentType_DeviceManual() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15093L));
  }

  static ExpandedNodeId initComponentType_ComponentName() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15099L));
  }

  static ExpandedNodeId initComponentType_SoftwareRevision() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15090L));
  }

  static ExpandedNodeId initComponentType_ProductInstanceUri() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15096L));
  }

  static ExpandedNodeId initComponentType_AssetId() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15098L));
  }

  static ExpandedNodeId initComponentType_ManufacturerUri() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15087L));
  }

  static ExpandedNodeId initComponentType_DeviceRevision() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15091L));
  }

  static ExpandedNodeId initDeviceType_DeviceHealth() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6208L));
  }

  static ExpandedNodeId initDeviceType_DeviceTypeImage_ImageIdentifier() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6210L));
  }

  static ExpandedNodeId initDeviceType_DeviceClass() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6470L));
  }

  static ExpandedNodeId initDeviceType_ManufacturerUri() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15100L));
  }

  static ExpandedNodeId initDeviceType_ImageSet_ImageIdentifier() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6216L));
  }

  static ExpandedNodeId initDeviceType_ProductCode() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15101L));
  }

  static ExpandedNodeId initDeviceType_Model() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6004L));
  }

  static ExpandedNodeId initDeviceType_ProtocolSupport_ProtocolSupportIdentifier() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6214L));
  }

  static ExpandedNodeId initDeviceType_DeviceManual() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6005L));
  }

  static ExpandedNodeId initDeviceType_ProductInstanceUri() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15102L));
  }

  static ExpandedNodeId initDeviceType_SerialNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6001L));
  }

  static ExpandedNodeId initDeviceType_Manufacturer() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6003L));
  }

  static ExpandedNodeId initDeviceType_RevisionCounter() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6002L));
  }

  static ExpandedNodeId initDeviceType_Documentation_DocumentIdentifier() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6212L));
  }

  static ExpandedNodeId initDeviceType_DeviceRevision() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6006L));
  }

  static ExpandedNodeId initDeviceType_HardwareRevision() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6008L));
  }

  static ExpandedNodeId initDeviceType_SoftwareRevision() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6007L));
  }

  static ExpandedNodeId initSoftwareType_SoftwareRevision() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15133L));
  }

  static ExpandedNodeId initSoftwareType_Manufacturer() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15129L));
  }

  static ExpandedNodeId initSoftwareType_Model() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15131L));
  }

  static ExpandedNodeId initBlockType_ActualMode() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6010L));
  }

  static ExpandedNodeId initBlockType_PermittedMode() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6011L));
  }

  static ExpandedNodeId initBlockType_RevisionCounter() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6009L));
  }

  static ExpandedNodeId initBlockType_NormalMode() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6012L));
  }

  static ExpandedNodeId initBlockType_TargetMode() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6013L));
  }

  static ExpandedNodeId initFunctionalGroupType_UIElement() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6243L));
  }

  static ExpandedNodeId initFunctionalGroupType_GroupIdentifier_UIElement() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6242L));
  }

  static ExpandedNodeId initDeviceHealthEnumeration_EnumStrings() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6450L));
  }

  static ExpandedNodeId initNetworkType_Lock_LockingClient() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6296L));
  }

  static ExpandedNodeId initNetworkType_Lock_InitLock_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6300L));
  }

  static ExpandedNodeId initNetworkType_Lock_InitLock_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6301L));
  }

  static ExpandedNodeId initNetworkType_Lock_RemainingLockTime() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6298L));
  }

  static ExpandedNodeId initNetworkType_Lock_Locked() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6497L));
  }

  static ExpandedNodeId initNetworkType_Lock_RenewLock_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6303L));
  }

  static ExpandedNodeId initNetworkType_Lock_ExitLock_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6305L));
  }

  static ExpandedNodeId initNetworkType_Lock_BreakLock_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6307L));
  }

  static ExpandedNodeId initNetworkType_Lock_LockingUser() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6297L));
  }

  static ExpandedNodeId initFetchResultDataType_DefaultXml_FetchResultDataType() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6539L));
  }

  static ExpandedNodeId initFetchResultDataType_DefaultBinary_FetchResultDataType() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6555L));
  }

  static ExpandedNodeId initTransferResultErrorDataType_DefaultXml_TransferResultErrorDataType() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15903L));
  }

  static ExpandedNodeId initTransferResultErrorDataType_DefaultBinary_TransferResultErrorDataType() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15894L));
  }

  static ExpandedNodeId initTransferResultDataDataType_DefaultBinary_TransferResultDataDataType() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15897L));
  }

  static ExpandedNodeId initTransferResultDataDataType_DefaultXml_TransferResultDataDataType() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15906L));
  }

  static ExpandedNodeId initParameterResultDataType_DefaultBinary_ParameterResultDataType() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6564L));
  }

  static ExpandedNodeId initParameterResultDataType_DefaultXml_ParameterResultDataType() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6548L));
  }

  static ExpandedNodeId initTransferServicesType_FetchTransferResultData_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6533L));
  }

  static ExpandedNodeId initTransferServicesType_TransferToDevice_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6528L));
  }

  static ExpandedNodeId initTransferServicesType_FetchTransferResultData_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6532L));
  }

  static ExpandedNodeId initTransferServicesType_TransferFromDevice_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6530L));
  }

  static ExpandedNodeId initLockingServicesType_DefaultInstanceBrowseName() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(15890L));
  }

  static ExpandedNodeId initLockingServicesType_RenewLock_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6397L));
  }

  static ExpandedNodeId initLockingServicesType_ExitLock_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6399L));
  }

  static ExpandedNodeId initLockingServicesType_LockingClient() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6390L));
  }

  static ExpandedNodeId initLockingServicesType_LockingUser() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6391L));
  }

  static ExpandedNodeId initLockingServicesType_Locked() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6534L));
  }

  static ExpandedNodeId initLockingServicesType_InitLock_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6394L));
  }

  static ExpandedNodeId initLockingServicesType_BreakLock_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6401L));
  }

  static ExpandedNodeId initLockingServicesType_RemainingLockTime() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6392L));
  }

  static ExpandedNodeId initLockingServicesType_InitLock_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6395L));
  }

  static ExpandedNodeId initSoftwareUpdateType_Installation_CurrentState_Id() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(42L));
  }

  static ExpandedNodeId initSoftwareUpdateType_Parameters_GenerateFileForRead_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(126L));
  }

  static ExpandedNodeId initSoftwareUpdateType_Installation_CurrentState() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(41L));
  }

  static ExpandedNodeId initSoftwareUpdateType_Parameters_GenerateFileForRead_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(125L));
  }

  static ExpandedNodeId initSoftwareUpdateType_Confirmation_CurrentState_Id() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(100L));
  }

  static ExpandedNodeId initSoftwareUpdateType_PrepareForUpdate_CurrentState() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(5L));
  }

  static ExpandedNodeId initSoftwareUpdateType_PrepareForUpdate_CurrentState_Id() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(6L));
  }

  static ExpandedNodeId initSoftwareUpdateType_UpdateStatus() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(133L));
  }

  static ExpandedNodeId initSoftwareUpdateType_Confirmation_ConfirmationTimeout() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(113L));
  }

  static ExpandedNodeId initSoftwareUpdateType_Parameters_GenerateFileForWrite_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(128L));
  }

  static ExpandedNodeId initSoftwareUpdateType_PowerCycle_CurrentState() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(77L));
  }

  static ExpandedNodeId initSoftwareUpdateType_DefaultInstanceBrowseName() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(134L));
  }

  static ExpandedNodeId initSoftwareUpdateType_VendorErrorCode() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(402L));
  }

  static ExpandedNodeId initSoftwareUpdateType_Parameters_GenerateFileForWrite_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(129L));
  }

  static ExpandedNodeId initSoftwareUpdateType_Parameters_CloseAndCommit_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(132L));
  }

  static ExpandedNodeId initSoftwareUpdateType_Parameters_ClientProcessingTimeout() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(123L));
  }

  static ExpandedNodeId initSoftwareUpdateType_Parameters_CloseAndCommit_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(131L));
  }

  static ExpandedNodeId initSoftwareUpdateType_PowerCycle_CurrentState_Id() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(78L));
  }

  static ExpandedNodeId initSoftwareUpdateType_Confirmation_CurrentState() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(99L));
  }

  static ExpandedNodeId initSoftwareLoadingType_UpdateKey() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(136L));
  }

  static ExpandedNodeId initPackageLoadingType_ErrorMessage() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(151L));
  }

  static ExpandedNodeId initPackageLoadingType_FileTransfer_CloseAndCommit_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(150L));
  }

  static ExpandedNodeId initPackageLoadingType_WriteBlockSize() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(152L));
  }

  static ExpandedNodeId initPackageLoadingType_FileTransfer_GenerateFileForWrite_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(146L));
  }

  static ExpandedNodeId initPackageLoadingType_CurrentVersion_SoftwareRevision() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(347L));
  }

  static ExpandedNodeId initPackageLoadingType_CurrentVersion_Manufacturer() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(345L));
  }

  static ExpandedNodeId initPackageLoadingType_FileTransfer_ClientProcessingTimeout() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(141L));
  }

  static ExpandedNodeId initPackageLoadingType_FileTransfer_GenerateFileForRead_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(144L));
  }

  static ExpandedNodeId initPackageLoadingType_FileTransfer_CloseAndCommit_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(149L));
  }

  static ExpandedNodeId initPackageLoadingType_FileTransfer_GenerateFileForRead_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(143L));
  }

  static ExpandedNodeId initPackageLoadingType_CurrentVersion_ManufacturerUri() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(346L));
  }

  static ExpandedNodeId initPackageLoadingType_FileTransfer_GenerateFileForWrite_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(147L));
  }

  static ExpandedNodeId initDirectLoadingType_WriteTimeout() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(170L));
  }

  static ExpandedNodeId initDirectLoadingType_UpdateBehavior() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(169L));
  }

  static ExpandedNodeId initCachedLoadingType_FallbackVersion_SoftwareRevision() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(375L));
  }

  static ExpandedNodeId initCachedLoadingType_PendingVersion_Manufacturer() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(366L));
  }

  static ExpandedNodeId initCachedLoadingType_PendingVersion_SoftwareRevision() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(368L));
  }

  static ExpandedNodeId initCachedLoadingType_GetUpdateBehavior_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(191L));
  }

  static ExpandedNodeId initCachedLoadingType_FallbackVersion_Manufacturer() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(373L));
  }

  static ExpandedNodeId initCachedLoadingType_FallbackVersion_ManufacturerUri() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(374L));
  }

  static ExpandedNodeId initCachedLoadingType_GetUpdateBehavior_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(190L));
  }

  static ExpandedNodeId initCachedLoadingType_PendingVersion_ManufacturerUri() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(367L));
  }

  static ExpandedNodeId initFileSystemLoadingType_FileSystem_CreateFile_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(199L));
  }

  static ExpandedNodeId initFileSystemLoadingType_GetUpdateBehavior_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(208L));
  }

  static ExpandedNodeId initFileSystemLoadingType_FileSystem_MoveOrCopy_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(204L));
  }

  static ExpandedNodeId initFileSystemLoadingType_FileSystem_CreateDirectory_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(196L));
  }

  static ExpandedNodeId initFileSystemLoadingType_ValidateFiles_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(211L));
  }

  static ExpandedNodeId initFileSystemLoadingType_ValidateFiles_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(210L));
  }

  static ExpandedNodeId initFileSystemLoadingType_GetUpdateBehavior_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(207L));
  }

  static ExpandedNodeId initFileSystemLoadingType_FileSystem_DeleteFileSystemObject_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(202L));
  }

  static ExpandedNodeId initFileSystemLoadingType_FileSystem_CreateFile_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(200L));
  }

  static ExpandedNodeId initFileSystemLoadingType_FileSystem_MoveOrCopy_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(205L));
  }

  static ExpandedNodeId initFileSystemLoadingType_FileSystem_CreateDirectory_OutputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(197L));
  }

  static ExpandedNodeId initSoftwareVersionType_Manufacturer() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(380L));
  }

  static ExpandedNodeId initSoftwareVersionType_PatchIdentifiers() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(383L));
  }

  static ExpandedNodeId initSoftwareVersionType_SoftwareRevision() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(382L));
  }

  static ExpandedNodeId initSoftwareVersionType_ReleaseDate() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(384L));
  }

  static ExpandedNodeId initSoftwareVersionType_ChangeLogReference() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(385L));
  }

  static ExpandedNodeId initSoftwareVersionType_ManufacturerUri() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(381L));
  }

  static ExpandedNodeId initSoftwareVersionType_Hash() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(386L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_PreparedForUpdateToResuming_TransitionNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(246L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_PreparingToIdle_Preparing_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(234L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_PreparingToPreparedForUpdate_TransitionNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(244L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_ResumingToIdle_TransitionNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(248L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_PreparedForUpdate_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(236L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_IdleToPreparing_Preparing_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(234L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_PreparedForUpdateToResuming_Resuming_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(238L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_Idle_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(232L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_PercentComplete() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(227L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_PreparingToIdle_TransitionNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(242L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_ResumingToIdle_Idle_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(232L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_PreparingToPreparedForUpdate_Preparing_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(234L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_PreparingToPreparedForUpdate_PreparedForUpdate_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(236L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_ResumingToIdle_Resuming_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(238L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_Resuming_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(238L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_Preparing_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(234L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_IdleToPreparing_Idle_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(232L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_PreparingToIdle_Idle_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(232L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_IdleToPreparing_TransitionNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(240L));
  }

  static ExpandedNodeId initPrepareForUpdateStateMachineType_PreparedForUpdateToResuming_PreparedForUpdate_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(236L));
  }

  static ExpandedNodeId initInstallationStateMachineType_InstallingToIdle_Idle_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(272L));
  }

  static ExpandedNodeId initInstallationStateMachineType_InstallationDelay() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(264L));
  }

  static ExpandedNodeId initInstallationStateMachineType_Error_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(276L));
  }

  static ExpandedNodeId initInstallationStateMachineType_IdleToInstalling_TransitionNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(387L));
  }

  static ExpandedNodeId initInstallationStateMachineType_ErrorToIdle_Idle_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(272L));
  }

  static ExpandedNodeId initInstallationStateMachineType_InstallingToIdle_TransitionNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(280L));
  }

  static ExpandedNodeId initInstallationStateMachineType_InstallSoftwarePackage_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(266L));
  }

  static ExpandedNodeId initInstallationStateMachineType_ErrorToIdle_TransitionNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(284L));
  }

  static ExpandedNodeId initInstallationStateMachineType_ErrorToIdle_Error_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(276L));
  }

  static ExpandedNodeId initInstallationStateMachineType_InstallingToError_Error_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(276L));
  }

  static ExpandedNodeId initInstallationStateMachineType_InstallFiles_InputArguments() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(269L));
  }

  static ExpandedNodeId initInstallationStateMachineType_IdleToInstalling_Installing_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(274L));
  }

  static ExpandedNodeId initInstallationStateMachineType_InstallingToIdle_Installing_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(274L));
  }

  static ExpandedNodeId initInstallationStateMachineType_PercentComplete() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(263L));
  }

  static ExpandedNodeId initInstallationStateMachineType_Idle_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(272L));
  }

  static ExpandedNodeId initInstallationStateMachineType_InstallingToError_Installing_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(274L));
  }

  static ExpandedNodeId initInstallationStateMachineType_IdleToInstalling_Idle_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(272L));
  }

  static ExpandedNodeId initInstallationStateMachineType_Installing_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(274L));
  }

  static ExpandedNodeId initInstallationStateMachineType_InstallingToError_TransitionNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(282L));
  }

  static ExpandedNodeId initPowerCycleStateMachineType_NotWaitingForPowerCycle_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(300L));
  }

  static ExpandedNodeId initPowerCycleStateMachineType_WaitingForPowerCycle_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(302L));
  }

  static ExpandedNodeId initPowerCycleStateMachineType_NotWaitingForPowerCycleToWaitingForPowerCycle_TransitionNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(304L));
  }

  static ExpandedNodeId initPowerCycleStateMachineType_NotWaitingForPowerCycleToWaitingForPowerCycle_WaitingForPowerCycle_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(302L));
  }

  static ExpandedNodeId initPowerCycleStateMachineType_WaitingForPowerCycleToNotWaitingForPowerCycle_WaitingForPowerCycle_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(302L));
  }

  static ExpandedNodeId initPowerCycleStateMachineType_WaitingForPowerCycleToNotWaitingForPowerCycle_NotWaitingForPowerCycle_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(300L));
  }

  static ExpandedNodeId initPowerCycleStateMachineType_NotWaitingForPowerCycleToWaitingForPowerCycle_NotWaitingForPowerCycle_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(300L));
  }

  static ExpandedNodeId initPowerCycleStateMachineType_WaitingForPowerCycleToNotWaitingForPowerCycle_TransitionNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(306L));
  }

  static ExpandedNodeId initConfirmationStateMachineType_ConfirmationTimeout() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(322L));
  }

  static ExpandedNodeId initConfirmationStateMachineType_WaitingForConfirmToNotWaitingForConfirm_WaitingForConfirm_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(326L));
  }

  static ExpandedNodeId initConfirmationStateMachineType_WaitingForConfirm_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(326L));
  }

  static ExpandedNodeId initConfirmationStateMachineType_NotWaitingForConfirmToWaitingForConfirm_WaitingForConfirm_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(326L));
  }

  static ExpandedNodeId initConfirmationStateMachineType_NotWaitingForConfirmToWaitingForConfirm_TransitionNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(328L));
  }

  static ExpandedNodeId initConfirmationStateMachineType_NotWaitingForConfirmToWaitingForConfirm_NotWaitingForConfirm_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(324L));
  }

  static ExpandedNodeId initConfirmationStateMachineType_WaitingForConfirmToNotWaitingForConfirm_NotWaitingForConfirm_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(324L));
  }

  static ExpandedNodeId initConfirmationStateMachineType_WaitingForConfirmToNotWaitingForConfirm_TransitionNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(330L));
  }

  static ExpandedNodeId initConfirmationStateMachineType_NotWaitingForConfirm_StateNumber() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(324L));
  }

  static ExpandedNodeId initSoftwareVersionFileType_EnumStrings() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(332L));
  }

  static ExpandedNodeId initUpdateBehavior_OptionSetValues() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/DI/", UnsignedInteger.valueOf(388L));
  }
}
