// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di;

import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.nodes.Optional;
import com.prosysopc.ua.types.opcua.FolderType;
import java.lang.Object;
import java.lang.String;

/**
 * FolderType is used to organize the Parameters and Methods from the complete set (ParameterSet, MethodSet) with regard to their application
 * <p>
 * Generated on 2022-10-10 10:21:30
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/DI/;i=1005")
public interface FunctionalGroupType extends FolderType {
  String GROUP_IDENTIFIER = "<GroupIdentifier>";

  String U_I_ELEMENT = "UIElement";

  @Optional
  UIElementType getUIElementNode();

  @Optional
  Object getUIElement();

  @Optional
  void setUIElement(Object value) throws StatusException;
}
