// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di;

import com.prosysopc.ua.UaNodeId;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

/**
 * Generated on 2024-06-17 14:43:47
 */
class InternalDIUaVariableTypeIdsHelper {
  public static final Set<UaNodeId> ALL_VARIABLETYPE_IDENTIFIERS;

  static {
    Set<UaNodeId> allIds = new HashSet<UaNodeId>();
    allIds.add(DIUaVariableTypeIds.LifetimeVariableType);
    allIds.add(DIUaVariableTypeIds.UIElementType);
    ALL_VARIABLETYPE_IDENTIFIERS = Collections.unmodifiableSet(allIds);
  }
}
