// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di;

import com.prosysopc.ua.UaNodeId;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

/**
 * Generated on 2025-04-16 18:27:23
 */
class InternalDIUaReferenceTypeIdsHelper {
  public static final Set<UaNodeId> ALL_REFERENCETYPE_IDENTIFIERS;

  static {
    Set<UaNodeId> allIds = new HashSet<UaNodeId>();
    allIds.add(DIUaReferenceTypeIds.ConnectsTo);
    allIds.add(DIUaReferenceTypeIds.ConnectsToParent);
    allIds.add(DIUaReferenceTypeIds.IsOnline);
    ALL_REFERENCETYPE_IDENTIFIERS = Collections.unmodifiableSet(allIds);
  }
}
