// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di;

import com.prosysopc.ua.StructureSerializer;
import com.prosysopc.ua.StructureUtils;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.UaNodeId;
import com.prosysopc.ua.stack.builtintypes.DiagnosticInfo;
import com.prosysopc.ua.stack.builtintypes.ExpandedNodeId;
import com.prosysopc.ua.stack.builtintypes.QualifiedName;
import com.prosysopc.ua.stack.builtintypes.StatusCode;
import com.prosysopc.ua.stack.builtintypes.Structure;
import com.prosysopc.ua.stack.encoding.EncoderContext;
import com.prosysopc.ua.stack.utils.AbstractStructure;
import com.prosysopc.ua.typedictionary.FieldSpecification;
import com.prosysopc.ua.typedictionary.StructureSpecification;
import java.lang.Class;
import java.lang.Deprecated;
import java.lang.IllegalArgumentException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;

/**
 * Generated on 2022-10-10 10:21:30
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/DI/;i=6525")
public class ParameterResultDataType extends AbstractStructure {
  @Deprecated
  public static final ExpandedNodeId BINARY = DIIds.ParameterResultDataType_DefaultBinary;

  @Deprecated
  public static final ExpandedNodeId XML = DIIds.ParameterResultDataType_DefaultXml;

  @Deprecated
  public static final ExpandedNodeId JSON = DIIds.ParameterResultDataType_DefaultJson;

  @Deprecated
  public static final ExpandedNodeId ID = DIIds.ParameterResultDataType;

  public static final StructureSpecification SPECIFICATION;

  static {
    StructureSpecification.Builder b = StructureSpecification.builder();
    b.addField(Fields.NodePath.getSpecification());
    b.addField(Fields.StatusCode.getSpecification());
    b.addField(Fields.Diagnostics.getSpecification());
    b.setBinaryEncodeId(UaNodeId.fromLocal(BINARY));
    b.setXmlEncodeId(UaNodeId.fromLocal(XML));
    b.setJsonEncodeId(UaNodeId.fromLocal(JSON));
    b.setTypeId(UaNodeId.fromLocal(ID));
    b.setName("ParameterResultDataType");
    b.setJavaClass(ParameterResultDataType.class);
    b.setStructureType(StructureSpecification.StructureType.NORMAL);
    b.setSerializerSupplier(new StructureSpecification.StructureSerializerSupplier() {
      @Override
      public StructureSerializer get(StructureSpecification specification, EncoderContext ctx) {
        return new DISerializers.ParameterResultDataTypeSerializer();
      }
    });
    b.setBuilderSupplier(new StructureSpecification.StructureBuilderSupplier() {
      @Override
      public Structure.Builder get() {
        return ParameterResultDataType.builder();
      }
    });
    SPECIFICATION = b.build();
  }

  private QualifiedName[] f_nodePath;

  private StatusCode f_statusCode;

  private DiagnosticInfo f_diagnostics;

  public ParameterResultDataType() {
  }

  public ParameterResultDataType(QualifiedName[] f_nodePath, StatusCode f_statusCode,
      DiagnosticInfo f_diagnostics) {
    this.f_nodePath = f_nodePath;
    this.f_statusCode = f_statusCode;
    this.f_diagnostics = f_diagnostics;
  }

  public QualifiedName[] getNodePath() {
    return this.f_nodePath;
  }

  public void setNodePath(QualifiedName[] f_nodePath) {
    this.f_nodePath=f_nodePath;
  }

  public StatusCode getStatusCode() {
    return this.f_statusCode;
  }

  public void setStatusCode(StatusCode f_statusCode) {
    this.f_statusCode=f_statusCode;
  }

  public DiagnosticInfo getDiagnostics() {
    return this.f_diagnostics;
  }

  public void setDiagnostics(DiagnosticInfo f_diagnostics) {
    this.f_diagnostics=f_diagnostics;
  }

  @Override
  public ParameterResultDataType clone() {
    ParameterResultDataType result = (ParameterResultDataType) super.clone();
    result.f_nodePath = StructureUtils.clone(this.f_nodePath);
    result.f_statusCode = StructureUtils.clone(this.f_statusCode);
    result.f_diagnostics = StructureUtils.clone(this.f_diagnostics);
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    ParameterResultDataType other = (ParameterResultDataType) obj;
    if (!StructureUtils.scalarOrArrayEquals(getNodePath(), other.getNodePath())) {
      return false;
    }
    if (!StructureUtils.scalarOrArrayEquals(getStatusCode(), other.getStatusCode())) {
      return false;
    }
    if (!StructureUtils.scalarOrArrayEquals(getDiagnostics(), other.getDiagnostics())) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return StructureUtils.hashCode(this.getNodePath(), this.getStatusCode(), this.getDiagnostics());
  }

  @Override
  public void clear() {
    super.clear();
    this.f_nodePath = null;
    this.f_statusCode = null;
    this.f_diagnostics = null;
  }

  @Override
  @Deprecated
  public ExpandedNodeId getBinaryEncodeId() {
    return BINARY;
  }

  @Override
  @Deprecated
  public ExpandedNodeId getXmlEncodeId() {
    return XML;
  }

  @Override
  @Deprecated
  public ExpandedNodeId getJsonEncodeId() {
    return JSON;
  }

  @Override
  @Deprecated
  public ExpandedNodeId getTypeId() {
    return ID;
  }

  @Override
  public StructureSpecification specification() {
    return SPECIFICATION;
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Object get(FieldSpecification field) {
    if (Fields.NodePath.getSpecification().equals(field)) {
      return getNodePath();
    }
    if (Fields.StatusCode.getSpecification().equals(field)) {
      return getStatusCode();
    }
    if (Fields.Diagnostics.getSpecification().equals(field)) {
      return getDiagnostics();
    }
    throw new IllegalArgumentException("Unknown field: " + field);
  }

  @Override
  public void set(FieldSpecification field, Object value) {
    if (Fields.NodePath.getSpecification().equals(field)) {
      setNodePath((QualifiedName[]) value);
      return;
    }
    if (Fields.StatusCode.getSpecification().equals(field)) {
      setStatusCode((StatusCode) value);
      return;
    }
    if (Fields.Diagnostics.getSpecification().equals(field)) {
      setDiagnostics((DiagnosticInfo) value);
      return;
    }
    throw new IllegalArgumentException("Unknown field: " + field);
  }

  @Override
  public Builder toBuilder() {
    Builder b = ParameterResultDataType.builder();
    b.setNodePath(getNodePath());
    b.setStatusCode(getStatusCode());
    b.setDiagnostics(getDiagnostics());
    return b;
  }

  public enum Fields {
    NodePath("NodePath", QualifiedName[].class, false, UaNodeId.fromLocal(ExpandedNodeId.parseExpandedNodeId("nsu=http://opcfoundation.org/UA/;i=20")), 1, false),

    StatusCode("StatusCode", StatusCode.class, false, UaNodeId.fromLocal(ExpandedNodeId.parseExpandedNodeId("nsu=http://opcfoundation.org/UA/;i=19")), -1, false),

    Diagnostics("Diagnostics", DiagnosticInfo.class, false, UaNodeId.fromLocal(ExpandedNodeId.parseExpandedNodeId("nsu=http://opcfoundation.org/UA/;i=25")), -1, false);

    private final FieldSpecification value;

    Fields(String name, Class<?> javaClass, boolean isOptional, UaNodeId dataTypeId, int valueRank,
        boolean allowSubTypes) {
      FieldSpecification.Builder b = FieldSpecification.builder();
      b.setName(name);
      b.setJavaClass(javaClass);
      b.setIsOptional(isOptional);
      b.setDataTypeId(dataTypeId);
      b.setValueRank(valueRank);
      b.setAllowSubTypes(allowSubTypes);
      this.value = b.build();
    }

    public FieldSpecification getSpecification() {
      return value;
    }
  }

  public static class Builder extends AbstractStructure.Builder {
    private QualifiedName[] f_nodePath;

    private StatusCode f_statusCode;

    private DiagnosticInfo f_diagnostics;

    protected Builder() {
    }

    public Builder setNodePath(QualifiedName[] f_nodePath) {
      this.f_nodePath=f_nodePath;
      return this;
    }

    public Builder setStatusCode(StatusCode f_statusCode) {
      this.f_statusCode=f_statusCode;
      return this;
    }

    public Builder setDiagnostics(DiagnosticInfo f_diagnostics) {
      this.f_diagnostics=f_diagnostics;
      return this;
    }

    @Override
    public Builder set(FieldSpecification field, Object value) {
      if (Fields.NodePath.getSpecification().equals(field)) {
        setNodePath((QualifiedName[]) value);
        return this;
      }
      if (Fields.StatusCode.getSpecification().equals(field)) {
        setStatusCode((StatusCode) value);
        return this;
      }
      if (Fields.Diagnostics.getSpecification().equals(field)) {
        setDiagnostics((DiagnosticInfo) value);
        return this;
      }
      throw new IllegalArgumentException("Unknown field: " + field);
    }

    @Override
    public StructureSpecification specification() {
      return ParameterResultDataType.SPECIFICATION;
    }

    @Override
    public ParameterResultDataType build() {
      return new ParameterResultDataType(f_nodePath, f_statusCode, f_diagnostics);
    }
  }
}
