// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di;

import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.types.opcua.FiniteStateMachineType;

/**
 * Generated on 2022-10-10 10:21:30
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/DI/;i=285")
public interface PowerCycleStateMachineType extends FiniteStateMachineType {
}
