// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di;

import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.types.opcua.BaseObjectType;

/**
 * General structure of a Protocol ObjectType
 * <p>
 * Generated on 2022-10-10 10:21:30
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/DI/;i=1006")
public interface ProtocolType extends BaseObjectType {
}
