// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke.objecttypes.server;

import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke.CommercialKitchenEquipmentUaIds;
import com.prosysopc.ua.server.ServerCodegenModel;

/**
 * Generated on 2024-06-17 14:43:51
 */
public class CommercialKitchenEquipmentServerObjectTypesInformationModel {
  public static final ServerCodegenModel MODEL;

  static {
    ServerCodegenModel.Builder b = ServerCodegenModel.builder();
    //BatchInformationType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1002
    b.addClass(CommercialKitchenEquipmentUaIds.BatchInformationType, BatchInformationTypeNode::new);
    //KitchenDeviceHAConfigType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1003
    b.addClass(CommercialKitchenEquipmentUaIds.KitchenDeviceHAConfigType, KitchenDeviceHAConfigTypeNode::new);
    //KitchenDeviceParameterType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1004
    b.addClass(CommercialKitchenEquipmentUaIds.KitchenDeviceParameterType, KitchenDeviceParameterTypeNode::new);
    //ChamberType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1012
    b.addClass(CommercialKitchenEquipmentUaIds.ChamberType, ChamberTypeNode::new);
    //CoffeeMachineParameterType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1022
    b.addClass(CommercialKitchenEquipmentUaIds.CoffeeMachineParameterType, CoffeeMachineParameterTypeNode::new);
    //CoffeeMachineRecipeParameterType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1023
    b.addClass(CommercialKitchenEquipmentUaIds.CoffeeMachineRecipeParameterType, CoffeeMachineRecipeParameterTypeNode::new);
    //CombiSteamerParameterType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1010
    b.addClass(CommercialKitchenEquipmentUaIds.CombiSteamerParameterType, CombiSteamerParameterTypeNode::new);
    //CookingKettleParameterType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1016
    b.addClass(CommercialKitchenEquipmentUaIds.CookingKettleParameterType, CookingKettleParameterTypeNode::new);
    //CookingZoneParameterType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1029
    b.addClass(CommercialKitchenEquipmentUaIds.CookingZoneParameterType, CookingZoneParameterTypeNode::new);
    //DishWashingMachineProgramParameterType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1025
    b.addClass(CommercialKitchenEquipmentUaIds.DishWashingMachineProgramParameterType, DishWashingMachineProgramParameterTypeNode::new);
    //FryerParameterType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1006
    b.addClass(CommercialKitchenEquipmentUaIds.FryerParameterType, FryerParameterTypeNode::new);
    //FryingAndGrillingParameterType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1031
    b.addClass(CommercialKitchenEquipmentUaIds.FryingAndGrillingParameterType, FryingAndGrillingParameterTypeNode::new);
    //FryingPanParameterType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1008
    b.addClass(CommercialKitchenEquipmentUaIds.FryingPanParameterType, FryingPanParameterTypeNode::new);
    //IceMachineParameterType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1035
    b.addClass(CommercialKitchenEquipmentUaIds.IceMachineParameterType, IceMachineParameterTypeNode::new);
    //MicrowaveCombiOvenParameterType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1033
    b.addClass(CommercialKitchenEquipmentUaIds.MicrowaveCombiOvenParameterType, MicrowaveCombiOvenParameterTypeNode::new);
    //MultiFunctionPanParameterType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1018
    b.addClass(CommercialKitchenEquipmentUaIds.MultiFunctionPanParameterType, MultiFunctionPanParameterTypeNode::new);
    //PastaCookerParameterType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1020
    b.addClass(CommercialKitchenEquipmentUaIds.PastaCookerParameterType, PastaCookerParameterTypeNode::new);
    //PressureCookingKettleParameterType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1014
    b.addClass(CommercialKitchenEquipmentUaIds.PressureCookingKettleParameterType, PressureCookingKettleParameterTypeNode::new);
    //TrayType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1027
    b.addClass(CommercialKitchenEquipmentUaIds.TrayType, TrayTypeNode::new);
    //CommercialKitchenDeviceType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1005
    b.addClass(CommercialKitchenEquipmentUaIds.CommercialKitchenDeviceType, CommercialKitchenDeviceTypeNode::new);
    //CoffeeMachineDeviceType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1024
    b.addClass(CommercialKitchenEquipmentUaIds.CoffeeMachineDeviceType, CoffeeMachineDeviceTypeNode::new);
    //CombiSteamerDeviceType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1011
    b.addClass(CommercialKitchenEquipmentUaIds.CombiSteamerDeviceType, CombiSteamerDeviceTypeNode::new);
    //CookingKettleDeviceType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1017
    b.addClass(CommercialKitchenEquipmentUaIds.CookingKettleDeviceType, CookingKettleDeviceTypeNode::new);
    //CookingZoneDeviceType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1030
    b.addClass(CommercialKitchenEquipmentUaIds.CookingZoneDeviceType, CookingZoneDeviceTypeNode::new);
    //DishWashingMachineDeviceType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1026
    b.addClass(CommercialKitchenEquipmentUaIds.DishWashingMachineDeviceType, DishWashingMachineDeviceTypeNode::new);
    //FryerDeviceType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1007
    b.addClass(CommercialKitchenEquipmentUaIds.FryerDeviceType, FryerDeviceTypeNode::new);
    //FryingAndGrillingDeviceType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1032
    b.addClass(CommercialKitchenEquipmentUaIds.FryingAndGrillingDeviceType, FryingAndGrillingDeviceTypeNode::new);
    //FryingPanDeviceType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1009
    b.addClass(CommercialKitchenEquipmentUaIds.FryingPanDeviceType, FryingPanDeviceTypeNode::new);
    //IceMachineDeviceType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1036
    b.addClass(CommercialKitchenEquipmentUaIds.IceMachineDeviceType, IceMachineDeviceTypeNode::new);
    //MicrowaveCombiOvenDeviceType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1034
    b.addClass(CommercialKitchenEquipmentUaIds.MicrowaveCombiOvenDeviceType, MicrowaveCombiOvenDeviceTypeNode::new);
    //MultiFunctionPanDeviceType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1019
    b.addClass(CommercialKitchenEquipmentUaIds.MultiFunctionPanDeviceType, MultiFunctionPanDeviceTypeNode::new);
    //OvenDeviceType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1013
    b.addClass(CommercialKitchenEquipmentUaIds.OvenDeviceType, OvenDeviceTypeNode::new);
    //PastaCookerDeviceType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1021
    b.addClass(CommercialKitchenEquipmentUaIds.PastaCookerDeviceType, PastaCookerDeviceTypeNode::new);
    //PressureCookingKettleDeviceType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1015
    b.addClass(CommercialKitchenEquipmentUaIds.PressureCookingKettleDeviceType, PressureCookingKettleDeviceTypeNode::new);
    //ServeryCounterDeviceType, nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=1028
    b.addClass(CommercialKitchenEquipmentUaIds.ServeryCounterDeviceType, ServeryCounterDeviceTypeNode::new);
    MODEL = b.build();
  }
}
