// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.objecttypes.server;

import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.objecttypes.BaseLifetimeIndicationType;
import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.nodes.UaNode;
import com.prosysopc.ua.server.GeneratedNodeInitializer;
import com.prosysopc.ua.server.ServiceContext;
import com.prosysopc.ua.stack.builtintypes.DiagnosticInfo;
import com.prosysopc.ua.stack.builtintypes.NodeId;
import com.prosysopc.ua.stack.builtintypes.StatusCode;
import com.prosysopc.ua.stack.builtintypes.Variant;
import com.prosysopc.ua.types.opcua.server.BaseObjectTypeNode;
import java.lang.Override;

/**
 * Base indication type not further defining a semantic
 * <p>
 * Generated on 2024-09-09 10:35:45
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/DI/;i=473")
public abstract class BaseLifetimeIndicationTypeNodeBase extends BaseObjectTypeNode implements BaseLifetimeIndicationType {
  private static GeneratedNodeInitializer<BaseLifetimeIndicationTypeNode> f_baseLifetimeIndicationTypeNodeInitializer;

  protected BaseLifetimeIndicationTypeNodeBase(UaNode.Parameters parameters) {
    super(parameters);
  }

  @Override
  public void afterCreate() {
    super.afterCreate();

    // Call afterCreate for each sub-node (if the node has any)
    GeneratedNodeInitializer<BaseLifetimeIndicationTypeNode> impl = getBaseLifetimeIndicationTypeNodeInitializer();
    if(impl != null) {
      impl.init((BaseLifetimeIndicationTypeNode)this);
    }
  }

  public static GeneratedNodeInitializer<BaseLifetimeIndicationTypeNode> getBaseLifetimeIndicationTypeNodeInitializer() {
    return f_baseLifetimeIndicationTypeNodeInitializer;
  }

  public static void setBaseLifetimeIndicationTypeNodeInitializer(GeneratedNodeInitializer<BaseLifetimeIndicationTypeNode> f_baseLifetimeIndicationTypeNodeInitializerNewValue) {
    f_baseLifetimeIndicationTypeNodeInitializer=f_baseLifetimeIndicationTypeNodeInitializerNewValue;
  }

  @Override
  public Variant[] callMethod(ServiceContext serviceContext, NodeId methodId,
      Variant[] inputArguments, StatusCode[] inputArgumentResults,
      DiagnosticInfo[] inputArgumentDiagnosticInfos) throws StatusException {
    return super.callMethod(serviceContext, methodId, inputArguments, inputArgumentResults, inputArgumentDiagnosticInfos);
  }
}
