// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.objecttypes.server;

import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.server.ServiceContext;

public abstract interface ConfirmationStateMachineTypeConfirmMethod {
  void confirm(ServiceContext serviceContext, ConfirmationStateMachineTypeNode node) throws
      StatusException;
}
