// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.objecttypes.server;

import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.objecttypes.MaintenanceRequiredAlarmType;
import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.nodes.UaNode;
import com.prosysopc.ua.server.GeneratedNodeInitializer;
import com.prosysopc.ua.server.ServiceContext;
import com.prosysopc.ua.stack.builtintypes.DiagnosticInfo;
import com.prosysopc.ua.stack.builtintypes.NodeId;
import com.prosysopc.ua.stack.builtintypes.StatusCode;
import com.prosysopc.ua.stack.builtintypes.Variant;
import java.lang.Override;

/**
 * Generated on 2025-04-16 18:27:23
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/DI/;i=15739")
public abstract class MaintenanceRequiredAlarmTypeNodeBase extends DeviceHealthDiagnosticAlarmTypeNode implements MaintenanceRequiredAlarmType {
  private static GeneratedNodeInitializer<MaintenanceRequiredAlarmTypeNode> f_maintenanceRequiredAlarmTypeNodeInitializer;

  protected MaintenanceRequiredAlarmTypeNodeBase(Parameters parameters) {
    super(parameters);
  }

  @Override
  public void afterCreate() {
    super.afterCreate();

    // Call afterCreate for each sub-node (if the node has any)
    GeneratedNodeInitializer<MaintenanceRequiredAlarmTypeNode> impl = getMaintenanceRequiredAlarmTypeNodeInitializer();
    if(impl != null) {
      impl.init((MaintenanceRequiredAlarmTypeNode)this);
    }
  }

  public static GeneratedNodeInitializer<MaintenanceRequiredAlarmTypeNode> getMaintenanceRequiredAlarmTypeNodeInitializer() {
    return f_maintenanceRequiredAlarmTypeNodeInitializer;
  }

  public static void setMaintenanceRequiredAlarmTypeNodeInitializer(GeneratedNodeInitializer<MaintenanceRequiredAlarmTypeNode> f_maintenanceRequiredAlarmTypeNodeInitializerNewValue) {
    f_maintenanceRequiredAlarmTypeNodeInitializer=f_maintenanceRequiredAlarmTypeNodeInitializerNewValue;
  }

  @Override
  public Variant[] callMethod(ServiceContext serviceContext, NodeId methodId,
      Variant[] inputArguments, StatusCode[] inputArgumentResults,
      DiagnosticInfo[] inputArgumentDiagnosticInfos) throws StatusException {
    return super.callMethod(serviceContext, methodId, inputArguments, inputArgumentResults, inputArgumentDiagnosticInfos);
  }
}
