// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.objecttypes.server;

import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.objecttypes.SoftwareVersionType;
import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.nodes.Mandatory;
import com.prosysopc.ua.nodes.Optional;
import com.prosysopc.ua.nodes.UaNode;
import com.prosysopc.ua.nodes.UaProperty;
import com.prosysopc.ua.nodes.UaVariable;
import com.prosysopc.ua.server.GeneratedNodeInitializer;
import com.prosysopc.ua.server.ServiceContext;
import com.prosysopc.ua.stack.builtintypes.ByteString;
import com.prosysopc.ua.stack.builtintypes.DateTime;
import com.prosysopc.ua.stack.builtintypes.DiagnosticInfo;
import com.prosysopc.ua.stack.builtintypes.LocalizedText;
import com.prosysopc.ua.stack.builtintypes.NodeId;
import com.prosysopc.ua.stack.builtintypes.QualifiedName;
import com.prosysopc.ua.stack.builtintypes.StatusCode;
import com.prosysopc.ua.stack.builtintypes.Variant;
import com.prosysopc.ua.types.opcua.server.BaseObjectTypeNode;
import java.lang.Object;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;

/**
 * Generated on 2023-09-26 10:56:50
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/DI/;i=212")
public abstract class SoftwareVersionTypeNodeBase extends BaseObjectTypeNode implements SoftwareVersionType {
  private static GeneratedNodeInitializer<SoftwareVersionTypeNode> f_softwareVersionTypeNodeInitializer;

  protected SoftwareVersionTypeNodeBase(UaNode.Parameters parameters) {
    super(parameters);
  }

  @Override
  public void afterCreate() {
    super.afterCreate();

    // Call afterCreate for each sub-node (if the node has any)
    GeneratedNodeInitializer<SoftwareVersionTypeNode> impl = getSoftwareVersionTypeNodeInitializer();
    if(impl != null) {
      impl.init((SoftwareVersionTypeNode)this);
    }
  }

  public static GeneratedNodeInitializer<SoftwareVersionTypeNode> getSoftwareVersionTypeNodeInitializer() {
    return f_softwareVersionTypeNodeInitializer;
  }

  public static void setSoftwareVersionTypeNodeInitializer(GeneratedNodeInitializer<SoftwareVersionTypeNode> f_softwareVersionTypeNodeInitializerNewValue) {
    f_softwareVersionTypeNodeInitializer=f_softwareVersionTypeNodeInitializerNewValue;
  }

  @Mandatory
  @Override
  public UaProperty getManufacturerNode() {
    QualifiedName browseName = getQualifiedName("http://opcfoundation.org/UA/DI/", "Manufacturer");
    return getProperty(browseName);
  }

  @Mandatory
  @Override
  public LocalizedText getManufacturer() {
    UaVariable node = getManufacturerNode();
    if (node == null) {
      throw new RuntimeException("Mandatory node Manufacturer does not exist");
    }
    Object value = node.getValue().getValue().getValue();
    return (LocalizedText) value;
  }

  @Mandatory
  @Override
  public void setManufacturer(LocalizedText value) {
    UaVariable node = getManufacturerNode();
    if (node == null) {
      throw new RuntimeException("Setting Manufacturer failed: does not exist (Optional Nodes must be configured in NodeBuilder)");
    }
    try {
      node.setValue(value);
    } catch(StatusException e) {
      throw new RuntimeException("Setting Manufacturer failed unexpectedly", e);
    }
  }

  @Mandatory
  @Override
  public UaProperty getManufacturerUriNode() {
    QualifiedName browseName = getQualifiedName("http://opcfoundation.org/UA/DI/", "ManufacturerUri");
    return getProperty(browseName);
  }

  @Mandatory
  @Override
  public String getManufacturerUri() {
    UaVariable node = getManufacturerUriNode();
    if (node == null) {
      throw new RuntimeException("Mandatory node ManufacturerUri does not exist");
    }
    Object value = node.getValue().getValue().getValue();
    return (String) value;
  }

  @Mandatory
  @Override
  public void setManufacturerUri(String value) {
    UaVariable node = getManufacturerUriNode();
    if (node == null) {
      throw new RuntimeException("Setting ManufacturerUri failed: does not exist (Optional Nodes must be configured in NodeBuilder)");
    }
    try {
      node.setValue(value);
    } catch(StatusException e) {
      throw new RuntimeException("Setting ManufacturerUri failed unexpectedly", e);
    }
  }

  @Mandatory
  @Override
  public UaProperty getSoftwareRevisionNode() {
    QualifiedName browseName = getQualifiedName("http://opcfoundation.org/UA/DI/", "SoftwareRevision");
    return getProperty(browseName);
  }

  @Mandatory
  @Override
  public String getSoftwareRevision() {
    UaVariable node = getSoftwareRevisionNode();
    if (node == null) {
      throw new RuntimeException("Mandatory node SoftwareRevision does not exist");
    }
    Object value = node.getValue().getValue().getValue();
    return (String) value;
  }

  @Mandatory
  @Override
  public void setSoftwareRevision(String value) {
    UaVariable node = getSoftwareRevisionNode();
    if (node == null) {
      throw new RuntimeException("Setting SoftwareRevision failed: does not exist (Optional Nodes must be configured in NodeBuilder)");
    }
    try {
      node.setValue(value);
    } catch(StatusException e) {
      throw new RuntimeException("Setting SoftwareRevision failed unexpectedly", e);
    }
  }

  @Optional
  @Override
  public UaProperty getPatchIdentifiersNode() {
    QualifiedName browseName = getQualifiedName("http://opcfoundation.org/UA/DI/", "PatchIdentifiers");
    return getProperty(browseName);
  }

  @Optional
  @Override
  public String[] getPatchIdentifiers() {
    UaVariable node = getPatchIdentifiersNode();
    if (node == null) {
      return null;
    }
    Object value = node.getValue().getValue().getValue();
    return (String[]) value;
  }

  @Optional
  @Override
  public void setPatchIdentifiers(String[] value) {
    UaVariable node = getPatchIdentifiersNode();
    if (node == null) {
      throw new RuntimeException("Setting PatchIdentifiers failed: does not exist (Optional Nodes must be configured in NodeBuilder)");
    }
    try {
      node.setValue(value);
    } catch(StatusException e) {
      throw new RuntimeException("Setting PatchIdentifiers failed unexpectedly", e);
    }
  }

  @Optional
  @Override
  public UaProperty getReleaseDateNode() {
    QualifiedName browseName = getQualifiedName("http://opcfoundation.org/UA/DI/", "ReleaseDate");
    return getProperty(browseName);
  }

  @Optional
  @Override
  public DateTime getReleaseDate() {
    UaVariable node = getReleaseDateNode();
    if (node == null) {
      return null;
    }
    Object value = node.getValue().getValue().getValue();
    return (DateTime) value;
  }

  @Optional
  @Override
  public void setReleaseDate(DateTime value) {
    UaVariable node = getReleaseDateNode();
    if (node == null) {
      throw new RuntimeException("Setting ReleaseDate failed: does not exist (Optional Nodes must be configured in NodeBuilder)");
    }
    try {
      node.setValue(value);
    } catch(StatusException e) {
      throw new RuntimeException("Setting ReleaseDate failed unexpectedly", e);
    }
  }

  @Optional
  @Override
  public UaProperty getChangeLogReferenceNode() {
    QualifiedName browseName = getQualifiedName("http://opcfoundation.org/UA/DI/", "ChangeLogReference");
    return getProperty(browseName);
  }

  @Optional
  @Override
  public String getChangeLogReference() {
    UaVariable node = getChangeLogReferenceNode();
    if (node == null) {
      return null;
    }
    Object value = node.getValue().getValue().getValue();
    return (String) value;
  }

  @Optional
  @Override
  public void setChangeLogReference(String value) {
    UaVariable node = getChangeLogReferenceNode();
    if (node == null) {
      throw new RuntimeException("Setting ChangeLogReference failed: does not exist (Optional Nodes must be configured in NodeBuilder)");
    }
    try {
      node.setValue(value);
    } catch(StatusException e) {
      throw new RuntimeException("Setting ChangeLogReference failed unexpectedly", e);
    }
  }

  @Optional
  @Override
  public UaProperty getHashNode() {
    QualifiedName browseName = getQualifiedName("http://opcfoundation.org/UA/DI/", "Hash");
    return getProperty(browseName);
  }

  @Optional
  @Override
  public ByteString getHash() {
    UaVariable node = getHashNode();
    if (node == null) {
      return null;
    }
    Object value = node.getValue().getValue().getValue();
    return (ByteString) value;
  }

  @Optional
  @Override
  public void setHash(ByteString value) {
    UaVariable node = getHashNode();
    if (node == null) {
      throw new RuntimeException("Setting Hash failed: does not exist (Optional Nodes must be configured in NodeBuilder)");
    }
    try {
      node.setValue(value);
    } catch(StatusException e) {
      throw new RuntimeException("Setting Hash failed unexpectedly", e);
    }
  }

  @Override
  public Variant[] callMethod(ServiceContext serviceContext, NodeId methodId,
      Variant[] inputArguments, StatusCode[] inputArgumentResults,
      DiagnosticInfo[] inputArgumentDiagnosticInfos) throws StatusException {
    return super.callMethod(serviceContext, methodId, inputArguments, inputArgumentResults, inputArgumentDiagnosticInfos);
  }
}
