// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.objecttypes.server;

import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.objecttypes.TransferServicesType;
import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.server.ServiceContext;

public abstract interface TransferServicesTypeTransferToDeviceMethod {
  TransferServicesType.TransferToDeviceMethodOutputs transferToDevice(ServiceContext serviceContext,
      TransferServicesTypeNode node) throws StatusException;
}
