// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.variabletypes.server;

import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.variabletypes.UIElementType;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.nodes.UaNode;
import com.prosysopc.ua.server.GeneratedNodeInitializer;
import com.prosysopc.ua.types.opcua.server.BaseDataVariableTypeNode;
import java.lang.Override;

/**
 * The base type for all UI Element Types.
 * <p>
 * Generated on 2024-06-17 14:43:47
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/DI/;i=6246")
public abstract class UIElementTypeNodeBase extends BaseDataVariableTypeNode implements UIElementType {
  private static GeneratedNodeInitializer<UIElementTypeNode> f_uIElementTypeNodeInitializer;

  protected UIElementTypeNodeBase(UaNode.Parameters parameters) {
    super(parameters);
  }

  @Override
  public void afterCreate() {
    super.afterCreate();

    // Call afterCreate for each sub-node (if the node has any)
    GeneratedNodeInitializer<UIElementTypeNode> impl = getUIElementTypeNodeInitializer();
    if(impl != null) {
      impl.init((UIElementTypeNode)this);
    }
  }

  public static GeneratedNodeInitializer<UIElementTypeNode> getUIElementTypeNodeInitializer() {
    return f_uIElementTypeNodeInitializer;
  }

  public static void setUIElementTypeNodeInitializer(GeneratedNodeInitializer<UIElementTypeNode> f_uIElementTypeNodeInitializerNewValue) {
    f_uIElementTypeNodeInitializer=f_uIElementTypeNodeInitializerNewValue;
  }
}
