// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke.datatypes;

import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke.CommercialKitchenEquipmentUaIds;
import com.prosysopc.ua.InternalUaDataTypeSpecificationMappings;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.stack.builtintypes.Enumeration;
import com.prosysopc.ua.stack.builtintypes.UnsignedInteger;
import com.prosysopc.ua.typedictionary.EnumerationSpecification;
import java.lang.IllegalArgumentException;
import java.lang.Integer;
import java.lang.Override;
import java.util.ArrayList;
import java.util.Collection;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated on 2025-04-16 18:27:26
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3015")
public enum CoffeeMachineModeEnumeration implements Enumeration {
  Off(0),

  Standby(1),

  Error(2),

  Cleaning(3);

  public static final EnumerationSpecification SPECIFICATION;

  public static final EnumSet<CoffeeMachineModeEnumeration> NONE = EnumSet.noneOf(CoffeeMachineModeEnumeration.class);

  public static final EnumSet<CoffeeMachineModeEnumeration> ALL = EnumSet.allOf(CoffeeMachineModeEnumeration.class);

  private static final Map<Integer, CoffeeMachineModeEnumeration> map;

  static {
    map = new HashMap<Integer,CoffeeMachineModeEnumeration>();
    for (CoffeeMachineModeEnumeration i : CoffeeMachineModeEnumeration.values()) {
      map.put(i.value, i);
    }
    EnumerationSpecification.Builder b = EnumerationSpecification.builder();
    b.setName("CoffeeMachineModeEnumeration");
    b.setJavaClass(CoffeeMachineModeEnumeration.class);
    b.setTypeId(CommercialKitchenEquipmentUaIds.CoffeeMachineModeEnumeration);
    b.addMapping(0, "Off");
    b.addMapping(1, "Standby");
    b.addMapping(2, "Error");
    b.addMapping(3, "Cleaning");
    b.setBuilderSupplier(new EnumerationSpecification.EnumerationBuilderSupplier() {
      @Override
      public Enumeration.Builder get() {
        return CoffeeMachineModeEnumeration.builder();
      }
    });
    SPECIFICATION = b.build();
    InternalUaDataTypeSpecificationMappings.put(CoffeeMachineModeEnumeration.class, SPECIFICATION);
  }

  private final int value;

  CoffeeMachineModeEnumeration(int value) {
    this.value = value;
  }

  @Override
  public EnumerationSpecification specification() {
    return SPECIFICATION;
  }

  public static CoffeeMachineModeEnumeration valueOf(int value) {
    return map.get(value);
  }

  public static CoffeeMachineModeEnumeration valueOf(Integer value) {
    return value == null ? null : valueOf(value.intValue());
  }

  public static CoffeeMachineModeEnumeration valueOf(UnsignedInteger value) {
    return value == null ? null : valueOf(value.intValue());
  }

  public static CoffeeMachineModeEnumeration[] valueOf(int[] value) {
    CoffeeMachineModeEnumeration[] result = new CoffeeMachineModeEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static CoffeeMachineModeEnumeration[] valueOf(Integer[] value) {
    CoffeeMachineModeEnumeration[] result = new CoffeeMachineModeEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static CoffeeMachineModeEnumeration[] valueOf(UnsignedInteger[] value) {
    CoffeeMachineModeEnumeration[] result = new CoffeeMachineModeEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static UnsignedInteger getMask(CoffeeMachineModeEnumeration... list) {
    int result = 0;
    for (CoffeeMachineModeEnumeration c : list) {
      result |= c.value;
    }
    return UnsignedInteger.getFromBits(result);
  }

  public static UnsignedInteger getMask(Collection<CoffeeMachineModeEnumeration> list) {
    int result = 0;
    for (CoffeeMachineModeEnumeration c : list) {
      result |= c.value;
    }
    return UnsignedInteger.getFromBits(result);
  }

  public static EnumSet<CoffeeMachineModeEnumeration> getSet(UnsignedInteger mask) {
    return getSet(mask.intValue());
  }

  public static EnumSet<CoffeeMachineModeEnumeration> getSet(int mask) {
    List<CoffeeMachineModeEnumeration> res = new ArrayList<CoffeeMachineModeEnumeration>();
    for (CoffeeMachineModeEnumeration l : CoffeeMachineModeEnumeration.values()) {
      if ((mask & l.value) == l.value) {
        res.add(l);
      }
    }
    return EnumSet.copyOf(res);
  }

  @Override
  public int getValue() {
    return value;
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Builder toBuilder() {
    Builder b = builder();
    b.setValue(this.getValue());
    return b;
  }

  public static class Builder implements Enumeration.Builder {
    private CoffeeMachineModeEnumeration value;

    private Builder() {
    }

    @Override
    public CoffeeMachineModeEnumeration build() {
      return value;
    }

    @Override
    public Builder setValue(int value) {
      this.value=CoffeeMachineModeEnumeration.valueOf(value);
      if (this.value == null) {
        throw new IllegalArgumentException("Unknown enum CoffeeMachineModeEnumeration int value: " + value);
      }
      return this;
    }
  }
}
