// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke.datatypes;

import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke.CommercialKitchenEquipmentUaIds;
import com.prosysopc.ua.InternalUaDataTypeSpecificationMappings;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.stack.builtintypes.Enumeration;
import com.prosysopc.ua.stack.builtintypes.UnsignedInteger;
import com.prosysopc.ua.typedictionary.EnumerationSpecification;
import java.lang.IllegalArgumentException;
import java.lang.Integer;
import java.lang.Override;
import java.util.ArrayList;
import java.util.Collection;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated on 2025-04-16 18:27:26
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3010")
public enum CookingKettleModeEnumeration implements Enumeration {
  Off(0),

  Preheat(1),

  SoftCook(2),

  Cook(3),

  CookSlow(4),

  KeepWarming(5),

  Stiring(6),

  PresetStart(7),

  Error(8);

  public static final EnumerationSpecification SPECIFICATION;

  public static final EnumSet<CookingKettleModeEnumeration> NONE = EnumSet.noneOf(CookingKettleModeEnumeration.class);

  public static final EnumSet<CookingKettleModeEnumeration> ALL = EnumSet.allOf(CookingKettleModeEnumeration.class);

  private static final Map<Integer, CookingKettleModeEnumeration> map;

  static {
    map = new HashMap<Integer,CookingKettleModeEnumeration>();
    for (CookingKettleModeEnumeration i : CookingKettleModeEnumeration.values()) {
      map.put(i.value, i);
    }
    EnumerationSpecification.Builder b = EnumerationSpecification.builder();
    b.setName("CookingKettleModeEnumeration");
    b.setJavaClass(CookingKettleModeEnumeration.class);
    b.setTypeId(CommercialKitchenEquipmentUaIds.CookingKettleModeEnumeration);
    b.addMapping(0, "Off");
    b.addMapping(1, "Preheat");
    b.addMapping(2, "SoftCook");
    b.addMapping(3, "Cook");
    b.addMapping(4, "CookSlow");
    b.addMapping(5, "KeepWarming");
    b.addMapping(6, "Stiring");
    b.addMapping(7, "PresetStart");
    b.addMapping(8, "Error");
    b.setBuilderSupplier(new EnumerationSpecification.EnumerationBuilderSupplier() {
      @Override
      public Enumeration.Builder get() {
        return CookingKettleModeEnumeration.builder();
      }
    });
    SPECIFICATION = b.build();
    InternalUaDataTypeSpecificationMappings.put(CookingKettleModeEnumeration.class, SPECIFICATION);
  }

  private final int value;

  CookingKettleModeEnumeration(int value) {
    this.value = value;
  }

  @Override
  public EnumerationSpecification specification() {
    return SPECIFICATION;
  }

  public static CookingKettleModeEnumeration valueOf(int value) {
    return map.get(value);
  }

  public static CookingKettleModeEnumeration valueOf(Integer value) {
    return value == null ? null : valueOf(value.intValue());
  }

  public static CookingKettleModeEnumeration valueOf(UnsignedInteger value) {
    return value == null ? null : valueOf(value.intValue());
  }

  public static CookingKettleModeEnumeration[] valueOf(int[] value) {
    CookingKettleModeEnumeration[] result = new CookingKettleModeEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static CookingKettleModeEnumeration[] valueOf(Integer[] value) {
    CookingKettleModeEnumeration[] result = new CookingKettleModeEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static CookingKettleModeEnumeration[] valueOf(UnsignedInteger[] value) {
    CookingKettleModeEnumeration[] result = new CookingKettleModeEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static UnsignedInteger getMask(CookingKettleModeEnumeration... list) {
    int result = 0;
    for (CookingKettleModeEnumeration c : list) {
      result |= c.value;
    }
    return UnsignedInteger.getFromBits(result);
  }

  public static UnsignedInteger getMask(Collection<CookingKettleModeEnumeration> list) {
    int result = 0;
    for (CookingKettleModeEnumeration c : list) {
      result |= c.value;
    }
    return UnsignedInteger.getFromBits(result);
  }

  public static EnumSet<CookingKettleModeEnumeration> getSet(UnsignedInteger mask) {
    return getSet(mask.intValue());
  }

  public static EnumSet<CookingKettleModeEnumeration> getSet(int mask) {
    List<CookingKettleModeEnumeration> res = new ArrayList<CookingKettleModeEnumeration>();
    for (CookingKettleModeEnumeration l : CookingKettleModeEnumeration.values()) {
      if ((mask & l.value) == l.value) {
        res.add(l);
      }
    }
    return EnumSet.copyOf(res);
  }

  @Override
  public int getValue() {
    return value;
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Builder toBuilder() {
    Builder b = builder();
    b.setValue(this.getValue());
    return b;
  }

  public static class Builder implements Enumeration.Builder {
    private CookingKettleModeEnumeration value;

    private Builder() {
    }

    @Override
    public CookingKettleModeEnumeration build() {
      return value;
    }

    @Override
    public Builder setValue(int value) {
      this.value=CookingKettleModeEnumeration.valueOf(value);
      if (this.value == null) {
        throw new IllegalArgumentException("Unknown enum CookingKettleModeEnumeration int value: " + value);
      }
      return this;
    }
  }
}
