// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke.datatypes;

import com.prosysopc.ua.InternalUaDataTypeSpecificationMappings;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.UaNodeId;
import com.prosysopc.ua.stack.builtintypes.Enumeration;
import com.prosysopc.ua.stack.builtintypes.ExpandedNodeId;
import com.prosysopc.ua.stack.builtintypes.UnsignedInteger;
import com.prosysopc.ua.typedictionary.EnumerationSpecification;
import java.lang.IllegalArgumentException;
import java.lang.Integer;
import java.lang.Override;
import java.util.ArrayList;
import java.util.Collection;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated on 2024-06-17 14:43:51
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3002")
public enum EnergySourceEnumeration implements Enumeration {
  Electric(0),

  Gas(1),

  Steam(2);

  public static final EnumerationSpecification SPECIFICATION;

  public static final EnumSet<EnergySourceEnumeration> NONE = EnumSet.noneOf(EnergySourceEnumeration.class);

  public static final EnumSet<EnergySourceEnumeration> ALL = EnumSet.allOf(EnergySourceEnumeration.class);

  private static final Map<Integer, EnergySourceEnumeration> map;

  static {
    map = new HashMap<Integer,EnergySourceEnumeration>();
    for (EnergySourceEnumeration i : EnergySourceEnumeration.values()) {
      map.put(i.value, i);
    }
    EnumerationSpecification.Builder b = EnumerationSpecification.builder();
    b.setName("EnergySourceEnumeration");
    b.setJavaClass(EnergySourceEnumeration.class);
    b.setTypeId(UaNodeId.fromLocal(ExpandedNodeId.parseExpandedNodeId("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3002")));
    b.addMapping(0, "Electric");
    b.addMapping(1, "Gas");
    b.addMapping(2, "Steam");
    b.setBuilderSupplier(new EnumerationSpecification.EnumerationBuilderSupplier() {
      @Override
      public Enumeration.Builder get() {
        return EnergySourceEnumeration.builder();
      }
    });
    SPECIFICATION = b.build();
    InternalUaDataTypeSpecificationMappings.put(EnergySourceEnumeration.class, SPECIFICATION);
  }

  private final int value;

  EnergySourceEnumeration(int value) {
    this.value = value;
  }

  @Override
  public EnumerationSpecification specification() {
    return SPECIFICATION;
  }

  public static EnergySourceEnumeration valueOf(int value) {
    return map.get(value);
  }

  public static EnergySourceEnumeration valueOf(Integer value) {
    return value == null ? null : valueOf(value.intValue());
  }

  public static EnergySourceEnumeration valueOf(UnsignedInteger value) {
    return value == null ? null : valueOf(value.intValue());
  }

  public static EnergySourceEnumeration[] valueOf(int[] value) {
    EnergySourceEnumeration[] result = new EnergySourceEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static EnergySourceEnumeration[] valueOf(Integer[] value) {
    EnergySourceEnumeration[] result = new EnergySourceEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static EnergySourceEnumeration[] valueOf(UnsignedInteger[] value) {
    EnergySourceEnumeration[] result = new EnergySourceEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static UnsignedInteger getMask(EnergySourceEnumeration... list) {
    int result = 0;
    for (EnergySourceEnumeration c : list) {
      result |= c.value;
    }
    return UnsignedInteger.getFromBits(result);
  }

  public static UnsignedInteger getMask(Collection<EnergySourceEnumeration> list) {
    int result = 0;
    for (EnergySourceEnumeration c : list) {
      result |= c.value;
    }
    return UnsignedInteger.getFromBits(result);
  }

  public static EnumSet<EnergySourceEnumeration> getSet(UnsignedInteger mask) {
    return getSet(mask.intValue());
  }

  public static EnumSet<EnergySourceEnumeration> getSet(int mask) {
    List<EnergySourceEnumeration> res = new ArrayList<EnergySourceEnumeration>();
    for (EnergySourceEnumeration l : EnergySourceEnumeration.values()) {
      if ((mask & l.value) == l.value) {
        res.add(l);
      }
    }
    return EnumSet.copyOf(res);
  }

  @Override
  public int getValue() {
    return value;
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Builder toBuilder() {
    Builder b = builder();
    b.setValue(this.getValue());
    return b;
  }

  public static class Builder implements Enumeration.Builder {
    private EnergySourceEnumeration value;

    private Builder() {
    }

    @Override
    public EnergySourceEnumeration build() {
      return value;
    }

    @Override
    public Builder setValue(int value) {
      this.value=EnergySourceEnumeration.valueOf(value);
      if (this.value == null) {
        throw new IllegalArgumentException("Unknown enum EnergySourceEnumeration int value: " + value);
      }
      return this;
    }
  }
}
