// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke.datatypes;

import com.prosysopc.ua.InternalUaDataTypeSpecificationMappings;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.UaNodeId;
import com.prosysopc.ua.stack.builtintypes.Enumeration;
import com.prosysopc.ua.stack.builtintypes.ExpandedNodeId;
import com.prosysopc.ua.stack.builtintypes.UnsignedInteger;
import com.prosysopc.ua.typedictionary.EnumerationSpecification;
import java.lang.IllegalArgumentException;
import java.lang.Integer;
import java.lang.Override;
import java.util.ArrayList;
import java.util.Collection;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated on 2024-06-17 14:43:51
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3018")
public enum OperationModeEnumeration implements Enumeration {
  Init(0),

  MachineOff(1),

  Filling(2),

  FillingHeating(3),

  Heating(4),

  EnableOperation(5),

  ReadyForOperation(6),

  Operation(7),

  Cycle_pause(8),

  NotDefined1(9),

  SelfCleaning(10),

  NotDefined2(11),

  RemoteControl(12),

  ControllingOutputs(13),

  NotDefined3(14),

  Error(15);

  public static final EnumerationSpecification SPECIFICATION;

  public static final EnumSet<OperationModeEnumeration> NONE = EnumSet.noneOf(OperationModeEnumeration.class);

  public static final EnumSet<OperationModeEnumeration> ALL = EnumSet.allOf(OperationModeEnumeration.class);

  private static final Map<Integer, OperationModeEnumeration> map;

  static {
    map = new HashMap<Integer,OperationModeEnumeration>();
    for (OperationModeEnumeration i : OperationModeEnumeration.values()) {
      map.put(i.value, i);
    }
    EnumerationSpecification.Builder b = EnumerationSpecification.builder();
    b.setName("OperationModeEnumeration");
    b.setJavaClass(OperationModeEnumeration.class);
    b.setTypeId(UaNodeId.fromLocal(ExpandedNodeId.parseExpandedNodeId("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3018")));
    b.addMapping(0, "Init");
    b.addMapping(1, "MachineOff");
    b.addMapping(2, "Filling");
    b.addMapping(3, "FillingHeating");
    b.addMapping(4, "Heating");
    b.addMapping(5, "EnableOperation");
    b.addMapping(6, "ReadyForOperation");
    b.addMapping(7, "Operation");
    b.addMapping(8, "Cycle_pause");
    b.addMapping(9, "NotDefined1");
    b.addMapping(10, "SelfCleaning");
    b.addMapping(11, "NotDefined2");
    b.addMapping(12, "RemoteControl");
    b.addMapping(13, "ControllingOutputs");
    b.addMapping(14, "NotDefined3");
    b.addMapping(15, "Error");
    b.setBuilderSupplier(new EnumerationSpecification.EnumerationBuilderSupplier() {
      @Override
      public Enumeration.Builder get() {
        return OperationModeEnumeration.builder();
      }
    });
    SPECIFICATION = b.build();
    InternalUaDataTypeSpecificationMappings.put(OperationModeEnumeration.class, SPECIFICATION);
  }

  private final int value;

  OperationModeEnumeration(int value) {
    this.value = value;
  }

  @Override
  public EnumerationSpecification specification() {
    return SPECIFICATION;
  }

  public static OperationModeEnumeration valueOf(int value) {
    return map.get(value);
  }

  public static OperationModeEnumeration valueOf(Integer value) {
    return value == null ? null : valueOf(value.intValue());
  }

  public static OperationModeEnumeration valueOf(UnsignedInteger value) {
    return value == null ? null : valueOf(value.intValue());
  }

  public static OperationModeEnumeration[] valueOf(int[] value) {
    OperationModeEnumeration[] result = new OperationModeEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static OperationModeEnumeration[] valueOf(Integer[] value) {
    OperationModeEnumeration[] result = new OperationModeEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static OperationModeEnumeration[] valueOf(UnsignedInteger[] value) {
    OperationModeEnumeration[] result = new OperationModeEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static UnsignedInteger getMask(OperationModeEnumeration... list) {
    int result = 0;
    for (OperationModeEnumeration c : list) {
      result |= c.value;
    }
    return UnsignedInteger.getFromBits(result);
  }

  public static UnsignedInteger getMask(Collection<OperationModeEnumeration> list) {
    int result = 0;
    for (OperationModeEnumeration c : list) {
      result |= c.value;
    }
    return UnsignedInteger.getFromBits(result);
  }

  public static EnumSet<OperationModeEnumeration> getSet(UnsignedInteger mask) {
    return getSet(mask.intValue());
  }

  public static EnumSet<OperationModeEnumeration> getSet(int mask) {
    List<OperationModeEnumeration> res = new ArrayList<OperationModeEnumeration>();
    for (OperationModeEnumeration l : OperationModeEnumeration.values()) {
      if ((mask & l.value) == l.value) {
        res.add(l);
      }
    }
    return EnumSet.copyOf(res);
  }

  @Override
  public int getValue() {
    return value;
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Builder toBuilder() {
    Builder b = builder();
    b.setValue(this.getValue());
    return b;
  }

  public static class Builder implements Enumeration.Builder {
    private OperationModeEnumeration value;

    private Builder() {
    }

    @Override
    public OperationModeEnumeration build() {
      return value;
    }

    @Override
    public Builder setValue(int value) {
      this.value=OperationModeEnumeration.valueOf(value);
      if (this.value == null) {
        throw new IllegalArgumentException("Unknown enum OperationModeEnumeration int value: " + value);
      }
      return this;
    }
  }
}
