// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke.datatypes;

import com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke.CommercialKitchenEquipmentUaIds;
import com.prosysopc.ua.InternalUaDataTypeSpecificationMappings;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.stack.builtintypes.Enumeration;
import com.prosysopc.ua.stack.builtintypes.UnsignedInteger;
import com.prosysopc.ua.typedictionary.EnumerationSpecification;
import java.lang.IllegalArgumentException;
import java.lang.Integer;
import java.lang.Override;
import java.util.ArrayList;
import java.util.Collection;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated on 2024-09-09 10:35:47
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3016")
public enum ProgramModeEnumeration implements Enumeration {
  OperationOFF(0),

  PreWash(1),

  Cleaning1(2),

  WashTimeIncreased(3),

  Cleaning2(4),

  DrainingPause(5),

  Draining(6),

  FinalRinse(7),

  WaitingTime(8),

  HeatRecovery(9);

  public static final EnumerationSpecification SPECIFICATION;

  public static final EnumSet<ProgramModeEnumeration> NONE = EnumSet.noneOf(ProgramModeEnumeration.class);

  public static final EnumSet<ProgramModeEnumeration> ALL = EnumSet.allOf(ProgramModeEnumeration.class);

  private static final Map<Integer, ProgramModeEnumeration> map;

  static {
    map = new HashMap<Integer,ProgramModeEnumeration>();
    for (ProgramModeEnumeration i : ProgramModeEnumeration.values()) {
      map.put(i.value, i);
    }
    EnumerationSpecification.Builder b = EnumerationSpecification.builder();
    b.setName("ProgramModeEnumeration");
    b.setJavaClass(ProgramModeEnumeration.class);
    b.setTypeId(CommercialKitchenEquipmentUaIds.ProgramModeEnumeration);
    b.addMapping(0, "OperationOFF");
    b.addMapping(1, "PreWash");
    b.addMapping(2, "Cleaning1");
    b.addMapping(3, "WashTimeIncreased");
    b.addMapping(4, "Cleaning2");
    b.addMapping(5, "DrainingPause");
    b.addMapping(6, "Draining");
    b.addMapping(7, "FinalRinse");
    b.addMapping(8, "WaitingTime");
    b.addMapping(9, "HeatRecovery");
    b.setBuilderSupplier(new EnumerationSpecification.EnumerationBuilderSupplier() {
      @Override
      public Enumeration.Builder get() {
        return ProgramModeEnumeration.builder();
      }
    });
    SPECIFICATION = b.build();
    InternalUaDataTypeSpecificationMappings.put(ProgramModeEnumeration.class, SPECIFICATION);
  }

  private final int value;

  ProgramModeEnumeration(int value) {
    this.value = value;
  }

  @Override
  public EnumerationSpecification specification() {
    return SPECIFICATION;
  }

  public static ProgramModeEnumeration valueOf(int value) {
    return map.get(value);
  }

  public static ProgramModeEnumeration valueOf(Integer value) {
    return value == null ? null : valueOf(value.intValue());
  }

  public static ProgramModeEnumeration valueOf(UnsignedInteger value) {
    return value == null ? null : valueOf(value.intValue());
  }

  public static ProgramModeEnumeration[] valueOf(int[] value) {
    ProgramModeEnumeration[] result = new ProgramModeEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static ProgramModeEnumeration[] valueOf(Integer[] value) {
    ProgramModeEnumeration[] result = new ProgramModeEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static ProgramModeEnumeration[] valueOf(UnsignedInteger[] value) {
    ProgramModeEnumeration[] result = new ProgramModeEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static UnsignedInteger getMask(ProgramModeEnumeration... list) {
    int result = 0;
    for (ProgramModeEnumeration c : list) {
      result |= c.value;
    }
    return UnsignedInteger.getFromBits(result);
  }

  public static UnsignedInteger getMask(Collection<ProgramModeEnumeration> list) {
    int result = 0;
    for (ProgramModeEnumeration c : list) {
      result |= c.value;
    }
    return UnsignedInteger.getFromBits(result);
  }

  public static EnumSet<ProgramModeEnumeration> getSet(UnsignedInteger mask) {
    return getSet(mask.intValue());
  }

  public static EnumSet<ProgramModeEnumeration> getSet(int mask) {
    List<ProgramModeEnumeration> res = new ArrayList<ProgramModeEnumeration>();
    for (ProgramModeEnumeration l : ProgramModeEnumeration.values()) {
      if ((mask & l.value) == l.value) {
        res.add(l);
      }
    }
    return EnumSet.copyOf(res);
  }

  @Override
  public int getValue() {
    return value;
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Builder toBuilder() {
    Builder b = builder();
    b.setValue(this.getValue());
    return b;
  }

  public static class Builder implements Enumeration.Builder {
    private ProgramModeEnumeration value;

    private Builder() {
    }

    @Override
    public ProgramModeEnumeration build() {
      return value;
    }

    @Override
    public Builder setValue(int value) {
      this.value=ProgramModeEnumeration.valueOf(value);
      if (this.value == null) {
        throw new IllegalArgumentException("Unknown enum ProgramModeEnumeration int value: " + value);
      }
      return this;
    }
  }
}
