// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke.datatypes;

import com.prosysopc.ua.InternalUaDataTypeSpecificationMappings;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.UaNodeId;
import com.prosysopc.ua.stack.builtintypes.Enumeration;
import com.prosysopc.ua.stack.builtintypes.ExpandedNodeId;
import com.prosysopc.ua.stack.builtintypes.UnsignedInteger;
import com.prosysopc.ua.typedictionary.EnumerationSpecification;
import java.lang.IllegalArgumentException;
import java.lang.Integer;
import java.lang.Override;
import java.util.ArrayList;
import java.util.Collection;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated on 2024-06-17 14:43:51
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3004")
public enum SignalModeEnumeration implements Enumeration {
  SignalOff(0),

  SignalOn(1),

  SignalAck(2);

  public static final EnumerationSpecification SPECIFICATION;

  public static final EnumSet<SignalModeEnumeration> NONE = EnumSet.noneOf(SignalModeEnumeration.class);

  public static final EnumSet<SignalModeEnumeration> ALL = EnumSet.allOf(SignalModeEnumeration.class);

  private static final Map<Integer, SignalModeEnumeration> map;

  static {
    map = new HashMap<Integer,SignalModeEnumeration>();
    for (SignalModeEnumeration i : SignalModeEnumeration.values()) {
      map.put(i.value, i);
    }
    EnumerationSpecification.Builder b = EnumerationSpecification.builder();
    b.setName("SignalModeEnumeration");
    b.setJavaClass(SignalModeEnumeration.class);
    b.setTypeId(UaNodeId.fromLocal(ExpandedNodeId.parseExpandedNodeId("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3004")));
    b.addMapping(0, "SignalOff");
    b.addMapping(1, "SignalOn");
    b.addMapping(2, "SignalAck");
    b.setBuilderSupplier(new EnumerationSpecification.EnumerationBuilderSupplier() {
      @Override
      public Enumeration.Builder get() {
        return SignalModeEnumeration.builder();
      }
    });
    SPECIFICATION = b.build();
    InternalUaDataTypeSpecificationMappings.put(SignalModeEnumeration.class, SPECIFICATION);
  }

  private final int value;

  SignalModeEnumeration(int value) {
    this.value = value;
  }

  @Override
  public EnumerationSpecification specification() {
    return SPECIFICATION;
  }

  public static SignalModeEnumeration valueOf(int value) {
    return map.get(value);
  }

  public static SignalModeEnumeration valueOf(Integer value) {
    return value == null ? null : valueOf(value.intValue());
  }

  public static SignalModeEnumeration valueOf(UnsignedInteger value) {
    return value == null ? null : valueOf(value.intValue());
  }

  public static SignalModeEnumeration[] valueOf(int[] value) {
    SignalModeEnumeration[] result = new SignalModeEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static SignalModeEnumeration[] valueOf(Integer[] value) {
    SignalModeEnumeration[] result = new SignalModeEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static SignalModeEnumeration[] valueOf(UnsignedInteger[] value) {
    SignalModeEnumeration[] result = new SignalModeEnumeration[value.length];
    for (int i = 0; i < value.length; i++) {
      result[i] = valueOf(value[i]);
    }
    return result;
  }

  public static UnsignedInteger getMask(SignalModeEnumeration... list) {
    int result = 0;
    for (SignalModeEnumeration c : list) {
      result |= c.value;
    }
    return UnsignedInteger.getFromBits(result);
  }

  public static UnsignedInteger getMask(Collection<SignalModeEnumeration> list) {
    int result = 0;
    for (SignalModeEnumeration c : list) {
      result |= c.value;
    }
    return UnsignedInteger.getFromBits(result);
  }

  public static EnumSet<SignalModeEnumeration> getSet(UnsignedInteger mask) {
    return getSet(mask.intValue());
  }

  public static EnumSet<SignalModeEnumeration> getSet(int mask) {
    List<SignalModeEnumeration> res = new ArrayList<SignalModeEnumeration>();
    for (SignalModeEnumeration l : SignalModeEnumeration.values()) {
      if ((mask & l.value) == l.value) {
        res.add(l);
      }
    }
    return EnumSet.copyOf(res);
  }

  @Override
  public int getValue() {
    return value;
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public Builder toBuilder() {
    Builder b = builder();
    b.setValue(this.getValue());
    return b;
  }

  public static class Builder implements Enumeration.Builder {
    private SignalModeEnumeration value;

    private Builder() {
    }

    @Override
    public SignalModeEnumeration build() {
      return value;
    }

    @Override
    public Builder setValue(int value) {
      this.value=SignalModeEnumeration.valueOf(value);
      if (this.value == null) {
        throw new IllegalArgumentException("Unknown enum SignalModeEnumeration int value: " + value);
      }
      return this;
    }
  }
}
