// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke;

import com.prosysopc.ua.stack.builtintypes.ExpandedNodeId;

/**
 * Generated on 2022-10-10 10:21:34
 */
public interface CommercialKitchenEquipmentObjectTypeIds {
  ExpandedNodeId BatchInformationType = CommercialKitchenEquipmentObjectTypeIdsInit.initBatchInformationType();

  ExpandedNodeId KitchenDeviceHAConfigType = CommercialKitchenEquipmentObjectTypeIdsInit.initKitchenDeviceHAConfigType();

  ExpandedNodeId KitchenDeviceParameterType = CommercialKitchenEquipmentObjectTypeIdsInit.initKitchenDeviceParameterType();

  ExpandedNodeId ChamberType = CommercialKitchenEquipmentObjectTypeIdsInit.initChamberType();

  ExpandedNodeId CoffeeMachineParameterType = CommercialKitchenEquipmentObjectTypeIdsInit.initCoffeeMachineParameterType();

  ExpandedNodeId CoffeeMachineRecipeParameterType = CommercialKitchenEquipmentObjectTypeIdsInit.initCoffeeMachineRecipeParameterType();

  ExpandedNodeId CombiSteamerParameterType = CommercialKitchenEquipmentObjectTypeIdsInit.initCombiSteamerParameterType();

  ExpandedNodeId CookingKettleParameterType = CommercialKitchenEquipmentObjectTypeIdsInit.initCookingKettleParameterType();

  ExpandedNodeId CookingZoneParameterType = CommercialKitchenEquipmentObjectTypeIdsInit.initCookingZoneParameterType();

  ExpandedNodeId DishWashingMachineProgramParameterType = CommercialKitchenEquipmentObjectTypeIdsInit.initDishWashingMachineProgramParameterType();

  ExpandedNodeId FryerParameterType = CommercialKitchenEquipmentObjectTypeIdsInit.initFryerParameterType();

  ExpandedNodeId FryingAndGrillingParameterType = CommercialKitchenEquipmentObjectTypeIdsInit.initFryingAndGrillingParameterType();

  ExpandedNodeId FryingPanParameterType = CommercialKitchenEquipmentObjectTypeIdsInit.initFryingPanParameterType();

  ExpandedNodeId IceMachineParameterType = CommercialKitchenEquipmentObjectTypeIdsInit.initIceMachineParameterType();

  ExpandedNodeId MicrowaveCombiOvenParameterType = CommercialKitchenEquipmentObjectTypeIdsInit.initMicrowaveCombiOvenParameterType();

  ExpandedNodeId MultiFunctionPanParameterType = CommercialKitchenEquipmentObjectTypeIdsInit.initMultiFunctionPanParameterType();

  ExpandedNodeId PastaCookerParameterType = CommercialKitchenEquipmentObjectTypeIdsInit.initPastaCookerParameterType();

  ExpandedNodeId PressureCookingKettleParameterType = CommercialKitchenEquipmentObjectTypeIdsInit.initPressureCookingKettleParameterType();

  ExpandedNodeId TrayType = CommercialKitchenEquipmentObjectTypeIdsInit.initTrayType();

  ExpandedNodeId CommercialKitchenDeviceType = CommercialKitchenEquipmentObjectTypeIdsInit.initCommercialKitchenDeviceType();

  ExpandedNodeId CoffeeMachineDeviceType = CommercialKitchenEquipmentObjectTypeIdsInit.initCoffeeMachineDeviceType();

  ExpandedNodeId CombiSteamerDeviceType = CommercialKitchenEquipmentObjectTypeIdsInit.initCombiSteamerDeviceType();

  ExpandedNodeId CookingKettleDeviceType = CommercialKitchenEquipmentObjectTypeIdsInit.initCookingKettleDeviceType();

  ExpandedNodeId CookingZoneDeviceType = CommercialKitchenEquipmentObjectTypeIdsInit.initCookingZoneDeviceType();

  ExpandedNodeId DishWashingMachineDeviceType = CommercialKitchenEquipmentObjectTypeIdsInit.initDishWashingMachineDeviceType();

  ExpandedNodeId FryerDeviceType = CommercialKitchenEquipmentObjectTypeIdsInit.initFryerDeviceType();

  ExpandedNodeId FryingAndGrillingDeviceType = CommercialKitchenEquipmentObjectTypeIdsInit.initFryingAndGrillingDeviceType();

  ExpandedNodeId FryingPanDeviceType = CommercialKitchenEquipmentObjectTypeIdsInit.initFryingPanDeviceType();

  ExpandedNodeId IceMachineDeviceType = CommercialKitchenEquipmentObjectTypeIdsInit.initIceMachineDeviceType();

  ExpandedNodeId MicrowaveCombiOvenDeviceType = CommercialKitchenEquipmentObjectTypeIdsInit.initMicrowaveCombiOvenDeviceType();

  ExpandedNodeId MultiFunctionPanDeviceType = CommercialKitchenEquipmentObjectTypeIdsInit.initMultiFunctionPanDeviceType();

  ExpandedNodeId OvenDeviceType = CommercialKitchenEquipmentObjectTypeIdsInit.initOvenDeviceType();

  ExpandedNodeId PastaCookerDeviceType = CommercialKitchenEquipmentObjectTypeIdsInit.initPastaCookerDeviceType();

  ExpandedNodeId PressureCookingKettleDeviceType = CommercialKitchenEquipmentObjectTypeIdsInit.initPressureCookingKettleDeviceType();

  ExpandedNodeId ServeryCounterDeviceType = CommercialKitchenEquipmentObjectTypeIdsInit.initServeryCounterDeviceType();
}
