// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke;

import com.prosysopc.ua.stack.builtintypes.ExpandedNodeId;
import com.prosysopc.ua.stack.builtintypes.UnsignedInteger;

class CommercialKitchenEquipmentObjectIdsInit {
  static ExpandedNodeId initCommercialKitchenDeviceType_ErrorConditions() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5002L));
  }

  static ExpandedNodeId initCommercialKitchenDeviceType_InformationConditions() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5003L));
  }

  static ExpandedNodeId initCommercialKitchenDeviceType_BatchInformation() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5001L));
  }

  static ExpandedNodeId initCommercialKitchenDeviceType_HACCPValues() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5004L));
  }

  static ExpandedNodeId initCoffeeMachineDeviceType_Parameters() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5013L));
  }

  static ExpandedNodeId initCoffeeMachineDeviceType_RecipeName() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5014L));
  }

  static ExpandedNodeId initCombiSteamerDeviceType_CombiSteamer() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5007L));
  }

  static ExpandedNodeId initCookingKettleDeviceType_CookingKettle() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5010L));
  }

  static ExpandedNodeId initCookingZoneDeviceType_CookingZone__No__() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5017L));
  }

  static ExpandedNodeId initDishWashingMachineDeviceType_Parameters() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5015L));
  }

  static ExpandedNodeId initFryerDeviceType_FryerCup__No__() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5005L));
  }

  static ExpandedNodeId initFryingAndGrillingDeviceType_GrillingZone__No__() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5018L));
  }

  static ExpandedNodeId initFryingPanDeviceType_FryingPan() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5006L));
  }

  static ExpandedNodeId initIceMachineDeviceType_IceMachine() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5020L));
  }

  static ExpandedNodeId initMicrowaveCombiOvenDeviceType_MicrowaveCombiOven() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5019L));
  }

  static ExpandedNodeId initMultiFunctionPanDeviceType_MultiFunctionPan__No__() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5011L));
  }

  static ExpandedNodeId initOvenDeviceType_Chamber__No__() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5008L));
  }

  static ExpandedNodeId initPastaCookerDeviceType_PastaCooker() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5012L));
  }

  static ExpandedNodeId initPressureCookingKettleDeviceType_PressureCookingKettle() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5009L));
  }

  static ExpandedNodeId initServeryCounterDeviceType_Tray__No__() {
    return new ExpandedNodeId("http://opcfoundation.org/UA/CommercialKitchenEquipment/", UnsignedInteger.valueOf(5016L));
  }
}
