// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke;

import com.prosysopc.ua.stack.builtintypes.ExpandedNodeId;

/**
 * Generated on 2022-10-10 10:21:34
 */
public interface CommercialKitchenEquipmentDataTypeIds {
  ExpandedNodeId BeverageSMLEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initBeverageSMLEnumeration();

  ExpandedNodeId ChamberModeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initChamberModeEnumeration();

  ExpandedNodeId CoffeeMachineModeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initCoffeeMachineModeEnumeration();

  ExpandedNodeId CombiSteamerModeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initCombiSteamerModeEnumeration();

  ExpandedNodeId CookingKettleModeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initCookingKettleModeEnumeration();

  ExpandedNodeId CurrentStateEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initCurrentStateEnumeration();

  ExpandedNodeId EnergySourceEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initEnergySourceEnumeration();

  ExpandedNodeId FryerModeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initFryerModeEnumeration();

  ExpandedNodeId FryingPanModeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initFryingPanModeEnumeration();

  ExpandedNodeId GrillingZoneStateEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initGrillingZoneStateEnumeration();

  ExpandedNodeId HygieneModeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initHygieneModeEnumeration();

  ExpandedNodeId MultiFunctionPanModeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initMultiFunctionPanModeEnumeration();

  ExpandedNodeId OperatingModeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initOperatingModeEnumeration();

  ExpandedNodeId OperationModeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initOperationModeEnumeration();

  ExpandedNodeId PastaCookerModeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initPastaCookerModeEnumeration();

  ExpandedNodeId PlatenPositionStateEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initPlatenPositionStateEnumeration();

  ExpandedNodeId PressureCookingKettleModeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initPressureCookingKettleModeEnumeration();

  ExpandedNodeId ProgramModeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initProgramModeEnumeration();

  ExpandedNodeId SignalModeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initSignalModeEnumeration();

  ExpandedNodeId SpecialCookingModeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initSpecialCookingModeEnumeration();

  ExpandedNodeId SpecialFunctionModeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initSpecialFunctionModeEnumeration();

  ExpandedNodeId StatusEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initStatusEnumeration();

  ExpandedNodeId TrayModeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initTrayModeEnumeration();

  ExpandedNodeId TrayTypeEnumeration = CommercialKitchenEquipmentDataTypeIdsInit.initTrayTypeEnumeration();
}
