// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke;

/**
 * Generated on 2022-10-10 10:21:34
 */
public interface CommercialKitchenEquipmentIds extends CommercialKitchenEquipmentDataTypeIds, CommercialKitchenEquipmentVariableIds, CommercialKitchenEquipmentObjectTypeIds, CommercialKitchenEquipmentObjectIds {
}
