// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke;

import com.prosysopc.ua.stack.encoding.binary.IEncodeableSerializer;
import java.util.ArrayList;
import java.util.List;

/**
 * Generated on 2022-10-10 10:21:34
 */
public class CommercialKitchenEquipmentSerializers {
  public static final IEncodeableSerializer[] SERIALIZERS;

  static {
    List<IEncodeableSerializer> l = new ArrayList<IEncodeableSerializer>();
    SERIALIZERS = l.toArray(new IEncodeableSerializer[0]);
  }
}
