// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke;

/**
 * Generated on 2023-09-26 10:56:54
 */
public interface CommercialKitchenEquipmentUaIds extends CommercialKitchenEquipmentUaVariableIds, CommercialKitchenEquipmentUaDataTypeIds, CommercialKitchenEquipmentUaObjectTypeIds, CommercialKitchenEquipmentUaObjectIds {
}
