// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke;

import com.prosysopc.ua.stack.builtintypes.ExpandedNodeId;
import com.prosysopc.ua.typedictionary.GeneratedDataTypeDictionary;
import java.lang.String;

/**
 * Generated on 2022-10-10 10:21:34
 */
public class CommercialKitchenEquipmentDataTypeDictionaryHelper {
  public static GeneratedDataTypeDictionary createDataTypeDictionary() {
    GeneratedDataTypeDictionary r = new GeneratedDataTypeDictionary("http://opcfoundation.org/UA/CommercialKitchenEquipment/");
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3014"), "BeverageSMLEnumeration", BeverageSMLEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3008"), "ChamberModeEnumeration", ChamberModeEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3015"), "CoffeeMachineModeEnumeration", CoffeeMachineModeEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3006"), "CombiSteamerModeEnumeration", CombiSteamerModeEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3010"), "CookingKettleModeEnumeration", CookingKettleModeEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3021"), "CurrentStateEnumeration", CurrentStateEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3002"), "EnergySourceEnumeration", EnergySourceEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3003"), "FryerModeEnumeration", FryerModeEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3005"), "FryingPanModeEnumeration", FryingPanModeEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3025"), "GrillingZoneStateEnumeration", GrillingZoneStateEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3017"), "HygieneModeEnumeration", HygieneModeEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3011"), "MultiFunctionPanModeEnumeration", MultiFunctionPanModeEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3023"), "OperatingModeEnumeration", OperatingModeEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3018"), "OperationModeEnumeration", OperationModeEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3013"), "PastaCookerModeEnumeration", PastaCookerModeEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3022"), "PlatenPositionStateEnumeration", PlatenPositionStateEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3009"), "PressureCookingKettleModeEnumeration", PressureCookingKettleModeEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3016"), "ProgramModeEnumeration", ProgramModeEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3004"), "SignalModeEnumeration", SignalModeEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3007"), "SpecialCookingModeEnumeration", SpecialCookingModeEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3012"), "SpecialFunctionModeEnumeration", SpecialFunctionModeEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3024"), "StatusEnumeration", StatusEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3019"), "TrayModeEnumeration", TrayModeEnumeration.class);
    r.addTypeInformation(eni("nsu=http://opcfoundation.org/UA/CommercialKitchenEquipment/;i=3020"), "TrayTypeEnumeration", TrayTypeEnumeration.class);
    return r;
  }

  private static ExpandedNodeId eni(String id) {
    return ExpandedNodeId.parseExpandedNodeId(id);
  }
}
