// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke;

import com.prosysopc.ua.UaNodeId;

class CommercialKitchenEquipmentUaObjectIdsInit {
  static UaNodeId initCommercialKitchenDeviceType_InformationConditions() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5003L);
  }

  static UaNodeId initCommercialKitchenDeviceType_BatchInformation() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5001L);
  }

  static UaNodeId initCommercialKitchenDeviceType_ErrorConditions() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5002L);
  }

  static UaNodeId initCommercialKitchenDeviceType_HACCPValues() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5004L);
  }

  static UaNodeId initCoffeeMachineDeviceType_Parameters() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5013L);
  }

  static UaNodeId initCoffeeMachineDeviceType_RecipeName() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5014L);
  }

  static UaNodeId initCombiSteamerDeviceType_CombiSteamer() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5007L);
  }

  static UaNodeId initCookingKettleDeviceType_CookingKettle() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5010L);
  }

  static UaNodeId initCookingZoneDeviceType_CookingZone__No__() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5017L);
  }

  static UaNodeId initDishWashingMachineDeviceType_Parameters() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5015L);
  }

  static UaNodeId initFryerDeviceType_FryerCup__No__() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5005L);
  }

  static UaNodeId initFryingAndGrillingDeviceType_GrillingZone__No__() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5018L);
  }

  static UaNodeId initFryingPanDeviceType_FryingPan() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5006L);
  }

  static UaNodeId initIceMachineDeviceType_IceMachine() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5020L);
  }

  static UaNodeId initMicrowaveCombiOvenDeviceType_MicrowaveCombiOven() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5019L);
  }

  static UaNodeId initMultiFunctionPanDeviceType_MultiFunctionPan__No__() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5011L);
  }

  static UaNodeId initOvenDeviceType_Chamber__No__() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5008L);
  }

  static UaNodeId initPastaCookerDeviceType_PastaCooker() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5012L);
  }

  static UaNodeId initPressureCookingKettleDeviceType_PressureCookingKettle() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5009L);
  }

  static UaNodeId initServeryCounterDeviceType_Tray__No__() {
    return UaNodeId.numeric(CommercialKitchenEquipmentUaIdsInitHelper.NAMESPACE, 5016L);
  }
}
