// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke;

import com.prosysopc.ua.UaNodeId;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

/**
 * Generated on 2025-04-16 18:27:26
 */
public interface CommercialKitchenEquipmentUaIds extends CommercialKitchenEquipmentUaDataTypeIds, CommercialKitchenEquipmentUaVariableIds, CommercialKitchenEquipmentUaObjectTypeIds, CommercialKitchenEquipmentUaObjectIds {
  static Set<UaNodeId> allIdentifiers() {
    Set<UaNodeId> r = new HashSet<>();
    r.addAll(CommercialKitchenEquipmentUaDataTypeIds.allDataTypeIdentifiers());
    r.addAll(CommercialKitchenEquipmentUaVariableIds.allVariableIdentifiers());
    r.addAll(CommercialKitchenEquipmentUaObjectTypeIds.allObjectTypeIdentifiers());
    r.addAll(CommercialKitchenEquipmentUaObjectIds.allObjectIdentifiers());
    return Collections.unmodifiableSet(r);
  }
}
