// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.cke;

import com.prosysopc.ua.UaNodeId;

/**
 * Generated on 2023-09-26 10:56:54
 */
public interface CommercialKitchenEquipmentUaObjectTypeIds {
  UaNodeId BatchInformationType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initBatchInformationType();

  UaNodeId KitchenDeviceHAConfigType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initKitchenDeviceHAConfigType();

  UaNodeId KitchenDeviceParameterType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initKitchenDeviceParameterType();

  UaNodeId ChamberType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initChamberType();

  UaNodeId CoffeeMachineParameterType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initCoffeeMachineParameterType();

  UaNodeId CoffeeMachineRecipeParameterType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initCoffeeMachineRecipeParameterType();

  UaNodeId CombiSteamerParameterType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initCombiSteamerParameterType();

  UaNodeId CookingKettleParameterType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initCookingKettleParameterType();

  UaNodeId CookingZoneParameterType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initCookingZoneParameterType();

  UaNodeId DishWashingMachineProgramParameterType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initDishWashingMachineProgramParameterType();

  UaNodeId FryerParameterType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initFryerParameterType();

  UaNodeId FryingAndGrillingParameterType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initFryingAndGrillingParameterType();

  UaNodeId FryingPanParameterType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initFryingPanParameterType();

  UaNodeId IceMachineParameterType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initIceMachineParameterType();

  UaNodeId MicrowaveCombiOvenParameterType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initMicrowaveCombiOvenParameterType();

  UaNodeId MultiFunctionPanParameterType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initMultiFunctionPanParameterType();

  UaNodeId PastaCookerParameterType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initPastaCookerParameterType();

  UaNodeId PressureCookingKettleParameterType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initPressureCookingKettleParameterType();

  UaNodeId TrayType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initTrayType();

  UaNodeId CommercialKitchenDeviceType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initCommercialKitchenDeviceType();

  UaNodeId CoffeeMachineDeviceType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initCoffeeMachineDeviceType();

  UaNodeId CombiSteamerDeviceType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initCombiSteamerDeviceType();

  UaNodeId CookingKettleDeviceType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initCookingKettleDeviceType();

  UaNodeId CookingZoneDeviceType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initCookingZoneDeviceType();

  UaNodeId DishWashingMachineDeviceType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initDishWashingMachineDeviceType();

  UaNodeId FryerDeviceType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initFryerDeviceType();

  UaNodeId FryingAndGrillingDeviceType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initFryingAndGrillingDeviceType();

  UaNodeId FryingPanDeviceType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initFryingPanDeviceType();

  UaNodeId IceMachineDeviceType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initIceMachineDeviceType();

  UaNodeId MicrowaveCombiOvenDeviceType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initMicrowaveCombiOvenDeviceType();

  UaNodeId MultiFunctionPanDeviceType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initMultiFunctionPanDeviceType();

  UaNodeId OvenDeviceType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initOvenDeviceType();

  UaNodeId PastaCookerDeviceType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initPastaCookerDeviceType();

  UaNodeId PressureCookingKettleDeviceType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initPressureCookingKettleDeviceType();

  UaNodeId ServeryCounterDeviceType = CommercialKitchenEquipmentUaObjectTypeIdsInit.initServeryCounterDeviceType();
}
