// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.objecttypes;

import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.types.opcua.BaseObjectType;

/**
 * Base indication type not further defining a semantic
 * <p>
 * Generated on 2025-04-16 18:27:23
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/DI/;i=473")
public interface BaseLifetimeIndicationType extends BaseObjectType {
}
