// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.objecttypes;

import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.nodes.Optional;
import com.prosysopc.ua.nodes.UaProperty;
import com.prosysopc.ua.types.opcua.BaseInterfaceType;
import java.lang.Double;
import java.lang.Number;
import java.lang.String;

/**
 * Interface defining counters for the duration of operation
 * <p>
 * Generated on 2024-09-09 10:35:45
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/DI/;i=480")
public interface IOperationCounterType extends BaseInterfaceType {
  String POWER_ON_DURATION = "PowerOnDuration";

  String OPERATION_DURATION = "OperationDuration";

  String OPERATION_CYCLE_COUNTER = "OperationCycleCounter";

  @Optional
  UaProperty getPowerOnDurationNode();

  @Optional
  Double getPowerOnDuration();

  @Optional
  void setPowerOnDuration(Double value) throws StatusException;

  @Optional
  UaProperty getOperationDurationNode();

  @Optional
  Double getOperationDuration();

  @Optional
  void setOperationDuration(Double value) throws StatusException;

  @Optional
  UaProperty getOperationCycleCounterNode();

  @Optional
  Number getOperationCycleCounter();

  @Optional
  void setOperationCycleCounter(Number value) throws StatusException;
}
