// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.objecttypes;

import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.nodes.Mandatory;
import com.prosysopc.ua.nodes.Optional;
import com.prosysopc.ua.nodes.UaProperty;
import com.prosysopc.ua.stack.builtintypes.ByteString;
import com.prosysopc.ua.stack.builtintypes.DateTime;
import com.prosysopc.ua.stack.builtintypes.LocalizedText;
import com.prosysopc.ua.types.opcua.BaseObjectType;
import java.lang.String;

/**
 * Generated on 2025-04-16 18:27:23
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/DI/;i=212")
public interface SoftwareVersionType extends BaseObjectType {
  String MANUFACTURER = "Manufacturer";

  String MANUFACTURER_URI = "ManufacturerUri";

  String SOFTWARE_REVISION = "SoftwareRevision";

  String PATCH_IDENTIFIERS = "PatchIdentifiers";

  String RELEASE_DATE = "ReleaseDate";

  String CHANGE_LOG_REFERENCE = "ChangeLogReference";

  String HASH = "Hash";

  @Mandatory
  UaProperty getManufacturerNode();

  @Mandatory
  LocalizedText getManufacturer();

  @Mandatory
  void setManufacturer(LocalizedText value) throws StatusException;

  @Mandatory
  UaProperty getManufacturerUriNode();

  @Mandatory
  String getManufacturerUri();

  @Mandatory
  void setManufacturerUri(String value) throws StatusException;

  @Mandatory
  UaProperty getSoftwareRevisionNode();

  @Mandatory
  String getSoftwareRevision();

  @Mandatory
  void setSoftwareRevision(String value) throws StatusException;

  @Optional
  UaProperty getPatchIdentifiersNode();

  @Optional
  String[] getPatchIdentifiers();

  @Optional
  void setPatchIdentifiers(String[] value) throws StatusException;

  @Optional
  UaProperty getReleaseDateNode();

  @Optional
  DateTime getReleaseDate();

  @Optional
  void setReleaseDate(DateTime value) throws StatusException;

  @Optional
  UaProperty getChangeLogReferenceNode();

  @Optional
  String getChangeLogReference();

  @Optional
  void setChangeLogReference(String value) throws StatusException;

  @Optional
  UaProperty getHashNode();

  @Optional
  ByteString getHash();

  @Optional
  void setHash(ByteString value) throws StatusException;
}
