// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.objecttypes;

import com.prosysopc.ua.TypeDefinitionId;

/**
 * Indicates the volume of a substance, for example of a liquid.
 * <p>
 * Generated on 2025-04-16 18:27:23
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/DI/;i=479")
public interface SubstanceVolumeIndicationType extends BaseLifetimeIndicationType {
}
