// Generated by Prosys OPC UA Java SDK Codegen
//
package com.connectedcooking.opcua.dynamicnodemanager.examples.prosys.opc30200.model.di.objecttypes;

import com.prosysopc.ua.TypeDefinitionId;

/**
 * Indicates the time the entity has been in use or can still be used
 * <p>
 * Generated on 2025-04-16 18:27:23
 */
@TypeDefinitionId("nsu=http://opcfoundation.org/UA/DI/;i=474")
public interface TimeIndicationType extends BaseLifetimeIndicationType {
}
